package com.whty.euicc.base.pojo;

import java.util.Date;

public class BaseLogs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_LOGS.ID
     *
     * @mbggenerated Tue May 12 10:59:19 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_LOGS.USER_ID
     *
     * @mbggenerated Tue May 12 10:59:19 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_LOGS.OP_TYPE
     *
     * @mbggenerated Tue May 12 10:59:19 CST 2015
     */
    private String opType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_LOGS.OP_DATE
     *
     * @mbggenerated Tue May 12 10:59:19 CST 2015
     */
    private Date opDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_LOGS.REMARK
     *
     * @mbggenerated Tue May 12 10:59:19 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_LOGS.OBJECT_ID
     *
     * @mbggenerated Tue May 12 10:59:19 CST 2015
     */
    private String objectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_LOGS.TYPE
     *
     * @mbggenerated Tue May 12 10:59:19 CST 2015
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_LOGS.ID
     *
     * @return the value of BASE_LOGS.ID
     *
     * @mbggenerated Tue May 12 10:59:19 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_LOGS.ID
     *
     * @param id the value for BASE_LOGS.ID
     *
     * @mbggenerated Tue May 12 10:59:19 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_LOGS.USER_ID
     *
     * @return the value of BASE_LOGS.USER_ID
     *
     * @mbggenerated Tue May 12 10:59:19 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_LOGS.USER_ID
     *
     * @param userId the value for BASE_LOGS.USER_ID
     *
     * @mbggenerated Tue May 12 10:59:19 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_LOGS.OP_TYPE
     *
     * @return the value of BASE_LOGS.OP_TYPE
     *
     * @mbggenerated Tue May 12 10:59:19 CST 2015
     */
    public String getOpType() {
        return opType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_LOGS.OP_TYPE
     *
     * @param opType the value for BASE_LOGS.OP_TYPE
     *
     * @mbggenerated Tue May 12 10:59:19 CST 2015
     */
    public void setOpType(String opType) {
        this.opType = opType == null ? null : opType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_LOGS.OP_DATE
     *
     * @return the value of BASE_LOGS.OP_DATE
     *
     * @mbggenerated Tue May 12 10:59:19 CST 2015
     */
    public Date getOpDate() {
        return opDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_LOGS.OP_DATE
     *
     * @param opDate the value for BASE_LOGS.OP_DATE
     *
     * @mbggenerated Tue May 12 10:59:19 CST 2015
     */
    public void setOpDate(Date opDate) {
        this.opDate = opDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_LOGS.REMARK
     *
     * @return the value of BASE_LOGS.REMARK
     *
     * @mbggenerated Tue May 12 10:59:19 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_LOGS.REMARK
     *
     * @param remark the value for BASE_LOGS.REMARK
     *
     * @mbggenerated Tue May 12 10:59:19 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_LOGS.OBJECT_ID
     *
     * @return the value of BASE_LOGS.OBJECT_ID
     *
     * @mbggenerated Tue May 12 10:59:19 CST 2015
     */
    public String getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_LOGS.OBJECT_ID
     *
     * @param objectId the value for BASE_LOGS.OBJECT_ID
     *
     * @mbggenerated Tue May 12 10:59:19 CST 2015
     */
    public void setObjectId(String objectId) {
        this.objectId = objectId == null ? null : objectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_LOGS.TYPE
     *
     * @return the value of BASE_LOGS.TYPE
     *
     * @mbggenerated Tue May 12 10:59:19 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_LOGS.TYPE
     *
     * @param type the value for BASE_LOGS.TYPE
     *
     * @mbggenerated Tue May 12 10:59:19 CST 2015
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}