package com.whty.euicc.base.pojo;

import java.util.ArrayList;
import java.util.List;

public class BaseModulesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BASE_MODULES
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BASE_MODULES
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BASE_MODULES
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_MODULES
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public BaseModulesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_MODULES
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_MODULES
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_MODULES
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_MODULES
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_MODULES
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_MODULES
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_MODULES
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_MODULES
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_MODULES
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_MODULES
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BASE_MODULES
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andModuleIdIsNull() {
            addCriterion("MODULE_ID is null");
            return (Criteria) this;
        }

        public Criteria andModuleIdIsNotNull() {
            addCriterion("MODULE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andModuleIdEqualTo(String value) {
            addCriterion("MODULE_ID =", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdNotEqualTo(String value) {
            addCriterion("MODULE_ID <>", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdGreaterThan(String value) {
            addCriterion("MODULE_ID >", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdGreaterThanOrEqualTo(String value) {
            addCriterion("MODULE_ID >=", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdLessThan(String value) {
            addCriterion("MODULE_ID <", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdLessThanOrEqualTo(String value) {
            addCriterion("MODULE_ID <=", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdLike(String value) {
            addCriterion("MODULE_ID like", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdNotLike(String value) {
            addCriterion("MODULE_ID not like", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdIn(List<String> values) {
            addCriterion("MODULE_ID in", values, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdNotIn(List<String> values) {
            addCriterion("MODULE_ID not in", values, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdBetween(String value1, String value2) {
            addCriterion("MODULE_ID between", value1, value2, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdNotBetween(String value1, String value2) {
            addCriterion("MODULE_ID not between", value1, value2, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleNameIsNull() {
            addCriterion("MODULE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andModuleNameIsNotNull() {
            addCriterion("MODULE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andModuleNameEqualTo(String value) {
            addCriterion("MODULE_NAME =", value, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameNotEqualTo(String value) {
            addCriterion("MODULE_NAME <>", value, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameGreaterThan(String value) {
            addCriterion("MODULE_NAME >", value, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameGreaterThanOrEqualTo(String value) {
            addCriterion("MODULE_NAME >=", value, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameLessThan(String value) {
            addCriterion("MODULE_NAME <", value, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameLessThanOrEqualTo(String value) {
            addCriterion("MODULE_NAME <=", value, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameLike(String value) {
            addCriterion("MODULE_NAME like", value, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameNotLike(String value) {
            addCriterion("MODULE_NAME not like", value, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameIn(List<String> values) {
            addCriterion("MODULE_NAME in", values, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameNotIn(List<String> values) {
            addCriterion("MODULE_NAME not in", values, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameBetween(String value1, String value2) {
            addCriterion("MODULE_NAME between", value1, value2, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameNotBetween(String value1, String value2) {
            addCriterion("MODULE_NAME not between", value1, value2, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleUrlIsNull() {
            addCriterion("MODULE_URL is null");
            return (Criteria) this;
        }

        public Criteria andModuleUrlIsNotNull() {
            addCriterion("MODULE_URL is not null");
            return (Criteria) this;
        }

        public Criteria andModuleUrlEqualTo(String value) {
            addCriterion("MODULE_URL =", value, "moduleUrl");
            return (Criteria) this;
        }

        public Criteria andModuleUrlNotEqualTo(String value) {
            addCriterion("MODULE_URL <>", value, "moduleUrl");
            return (Criteria) this;
        }

        public Criteria andModuleUrlGreaterThan(String value) {
            addCriterion("MODULE_URL >", value, "moduleUrl");
            return (Criteria) this;
        }

        public Criteria andModuleUrlGreaterThanOrEqualTo(String value) {
            addCriterion("MODULE_URL >=", value, "moduleUrl");
            return (Criteria) this;
        }

        public Criteria andModuleUrlLessThan(String value) {
            addCriterion("MODULE_URL <", value, "moduleUrl");
            return (Criteria) this;
        }

        public Criteria andModuleUrlLessThanOrEqualTo(String value) {
            addCriterion("MODULE_URL <=", value, "moduleUrl");
            return (Criteria) this;
        }

        public Criteria andModuleUrlLike(String value) {
            addCriterion("MODULE_URL like", value, "moduleUrl");
            return (Criteria) this;
        }

        public Criteria andModuleUrlNotLike(String value) {
            addCriterion("MODULE_URL not like", value, "moduleUrl");
            return (Criteria) this;
        }

        public Criteria andModuleUrlIn(List<String> values) {
            addCriterion("MODULE_URL in", values, "moduleUrl");
            return (Criteria) this;
        }

        public Criteria andModuleUrlNotIn(List<String> values) {
            addCriterion("MODULE_URL not in", values, "moduleUrl");
            return (Criteria) this;
        }

        public Criteria andModuleUrlBetween(String value1, String value2) {
            addCriterion("MODULE_URL between", value1, value2, "moduleUrl");
            return (Criteria) this;
        }

        public Criteria andModuleUrlNotBetween(String value1, String value2) {
            addCriterion("MODULE_URL not between", value1, value2, "moduleUrl");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNull() {
            addCriterion("PARENT_ID is null");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNotNull() {
            addCriterion("PARENT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andParentIdEqualTo(String value) {
            addCriterion("PARENT_ID =", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotEqualTo(String value) {
            addCriterion("PARENT_ID <>", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThan(String value) {
            addCriterion("PARENT_ID >", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThanOrEqualTo(String value) {
            addCriterion("PARENT_ID >=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThan(String value) {
            addCriterion("PARENT_ID <", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThanOrEqualTo(String value) {
            addCriterion("PARENT_ID <=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLike(String value) {
            addCriterion("PARENT_ID like", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotLike(String value) {
            addCriterion("PARENT_ID not like", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdIn(List<String> values) {
            addCriterion("PARENT_ID in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotIn(List<String> values) {
            addCriterion("PARENT_ID not in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdBetween(String value1, String value2) {
            addCriterion("PARENT_ID between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotBetween(String value1, String value2) {
            addCriterion("PARENT_ID not between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andLeafTypeIsNull() {
            addCriterion("LEAF_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andLeafTypeIsNotNull() {
            addCriterion("LEAF_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andLeafTypeEqualTo(Short value) {
            addCriterion("LEAF_TYPE =", value, "leafType");
            return (Criteria) this;
        }

        public Criteria andLeafTypeNotEqualTo(Short value) {
            addCriterion("LEAF_TYPE <>", value, "leafType");
            return (Criteria) this;
        }

        public Criteria andLeafTypeGreaterThan(Short value) {
            addCriterion("LEAF_TYPE >", value, "leafType");
            return (Criteria) this;
        }

        public Criteria andLeafTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("LEAF_TYPE >=", value, "leafType");
            return (Criteria) this;
        }

        public Criteria andLeafTypeLessThan(Short value) {
            addCriterion("LEAF_TYPE <", value, "leafType");
            return (Criteria) this;
        }

        public Criteria andLeafTypeLessThanOrEqualTo(Short value) {
            addCriterion("LEAF_TYPE <=", value, "leafType");
            return (Criteria) this;
        }

        public Criteria andLeafTypeIn(List<Short> values) {
            addCriterion("LEAF_TYPE in", values, "leafType");
            return (Criteria) this;
        }

        public Criteria andLeafTypeNotIn(List<Short> values) {
            addCriterion("LEAF_TYPE not in", values, "leafType");
            return (Criteria) this;
        }

        public Criteria andLeafTypeBetween(Short value1, Short value2) {
            addCriterion("LEAF_TYPE between", value1, value2, "leafType");
            return (Criteria) this;
        }

        public Criteria andLeafTypeNotBetween(Short value1, Short value2) {
            addCriterion("LEAF_TYPE not between", value1, value2, "leafType");
            return (Criteria) this;
        }

        public Criteria andExpandedStatusIsNull() {
            addCriterion("EXPANDED_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andExpandedStatusIsNotNull() {
            addCriterion("EXPANDED_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andExpandedStatusEqualTo(Short value) {
            addCriterion("EXPANDED_STATUS =", value, "expandedStatus");
            return (Criteria) this;
        }

        public Criteria andExpandedStatusNotEqualTo(Short value) {
            addCriterion("EXPANDED_STATUS <>", value, "expandedStatus");
            return (Criteria) this;
        }

        public Criteria andExpandedStatusGreaterThan(Short value) {
            addCriterion("EXPANDED_STATUS >", value, "expandedStatus");
            return (Criteria) this;
        }

        public Criteria andExpandedStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("EXPANDED_STATUS >=", value, "expandedStatus");
            return (Criteria) this;
        }

        public Criteria andExpandedStatusLessThan(Short value) {
            addCriterion("EXPANDED_STATUS <", value, "expandedStatus");
            return (Criteria) this;
        }

        public Criteria andExpandedStatusLessThanOrEqualTo(Short value) {
            addCriterion("EXPANDED_STATUS <=", value, "expandedStatus");
            return (Criteria) this;
        }

        public Criteria andExpandedStatusIn(List<Short> values) {
            addCriterion("EXPANDED_STATUS in", values, "expandedStatus");
            return (Criteria) this;
        }

        public Criteria andExpandedStatusNotIn(List<Short> values) {
            addCriterion("EXPANDED_STATUS not in", values, "expandedStatus");
            return (Criteria) this;
        }

        public Criteria andExpandedStatusBetween(Short value1, Short value2) {
            addCriterion("EXPANDED_STATUS between", value1, value2, "expandedStatus");
            return (Criteria) this;
        }

        public Criteria andExpandedStatusNotBetween(Short value1, Short value2) {
            addCriterion("EXPANDED_STATUS not between", value1, value2, "expandedStatus");
            return (Criteria) this;
        }

        public Criteria andDisplayIndexIsNull() {
            addCriterion("DISPLAY_INDEX is null");
            return (Criteria) this;
        }

        public Criteria andDisplayIndexIsNotNull() {
            addCriterion("DISPLAY_INDEX is not null");
            return (Criteria) this;
        }

        public Criteria andDisplayIndexEqualTo(Short value) {
            addCriterion("DISPLAY_INDEX =", value, "displayIndex");
            return (Criteria) this;
        }

        public Criteria andDisplayIndexNotEqualTo(Short value) {
            addCriterion("DISPLAY_INDEX <>", value, "displayIndex");
            return (Criteria) this;
        }

        public Criteria andDisplayIndexGreaterThan(Short value) {
            addCriterion("DISPLAY_INDEX >", value, "displayIndex");
            return (Criteria) this;
        }

        public Criteria andDisplayIndexGreaterThanOrEqualTo(Short value) {
            addCriterion("DISPLAY_INDEX >=", value, "displayIndex");
            return (Criteria) this;
        }

        public Criteria andDisplayIndexLessThan(Short value) {
            addCriterion("DISPLAY_INDEX <", value, "displayIndex");
            return (Criteria) this;
        }

        public Criteria andDisplayIndexLessThanOrEqualTo(Short value) {
            addCriterion("DISPLAY_INDEX <=", value, "displayIndex");
            return (Criteria) this;
        }

        public Criteria andDisplayIndexIn(List<Short> values) {
            addCriterion("DISPLAY_INDEX in", values, "displayIndex");
            return (Criteria) this;
        }

        public Criteria andDisplayIndexNotIn(List<Short> values) {
            addCriterion("DISPLAY_INDEX not in", values, "displayIndex");
            return (Criteria) this;
        }

        public Criteria andDisplayIndexBetween(Short value1, Short value2) {
            addCriterion("DISPLAY_INDEX between", value1, value2, "displayIndex");
            return (Criteria) this;
        }

        public Criteria andDisplayIndexNotBetween(Short value1, Short value2) {
            addCriterion("DISPLAY_INDEX not between", value1, value2, "displayIndex");
            return (Criteria) this;
        }

        public Criteria andIsDisplayIsNull() {
            addCriterion("IS_DISPLAY is null");
            return (Criteria) this;
        }

        public Criteria andIsDisplayIsNotNull() {
            addCriterion("IS_DISPLAY is not null");
            return (Criteria) this;
        }

        public Criteria andIsDisplayEqualTo(Short value) {
            addCriterion("IS_DISPLAY =", value, "isDisplay");
            return (Criteria) this;
        }

        public Criteria andIsDisplayNotEqualTo(Short value) {
            addCriterion("IS_DISPLAY <>", value, "isDisplay");
            return (Criteria) this;
        }

        public Criteria andIsDisplayGreaterThan(Short value) {
            addCriterion("IS_DISPLAY >", value, "isDisplay");
            return (Criteria) this;
        }

        public Criteria andIsDisplayGreaterThanOrEqualTo(Short value) {
            addCriterion("IS_DISPLAY >=", value, "isDisplay");
            return (Criteria) this;
        }

        public Criteria andIsDisplayLessThan(Short value) {
            addCriterion("IS_DISPLAY <", value, "isDisplay");
            return (Criteria) this;
        }

        public Criteria andIsDisplayLessThanOrEqualTo(Short value) {
            addCriterion("IS_DISPLAY <=", value, "isDisplay");
            return (Criteria) this;
        }

        public Criteria andIsDisplayIn(List<Short> values) {
            addCriterion("IS_DISPLAY in", values, "isDisplay");
            return (Criteria) this;
        }

        public Criteria andIsDisplayNotIn(List<Short> values) {
            addCriterion("IS_DISPLAY not in", values, "isDisplay");
            return (Criteria) this;
        }

        public Criteria andIsDisplayBetween(Short value1, Short value2) {
            addCriterion("IS_DISPLAY between", value1, value2, "isDisplay");
            return (Criteria) this;
        }

        public Criteria andIsDisplayNotBetween(Short value1, Short value2) {
            addCriterion("IS_DISPLAY not between", value1, value2, "isDisplay");
            return (Criteria) this;
        }

        public Criteria andIconCssIsNull() {
            addCriterion("ICON_CSS is null");
            return (Criteria) this;
        }

        public Criteria andIconCssIsNotNull() {
            addCriterion("ICON_CSS is not null");
            return (Criteria) this;
        }

        public Criteria andIconCssEqualTo(String value) {
            addCriterion("ICON_CSS =", value, "iconCss");
            return (Criteria) this;
        }

        public Criteria andIconCssNotEqualTo(String value) {
            addCriterion("ICON_CSS <>", value, "iconCss");
            return (Criteria) this;
        }

        public Criteria andIconCssGreaterThan(String value) {
            addCriterion("ICON_CSS >", value, "iconCss");
            return (Criteria) this;
        }

        public Criteria andIconCssGreaterThanOrEqualTo(String value) {
            addCriterion("ICON_CSS >=", value, "iconCss");
            return (Criteria) this;
        }

        public Criteria andIconCssLessThan(String value) {
            addCriterion("ICON_CSS <", value, "iconCss");
            return (Criteria) this;
        }

        public Criteria andIconCssLessThanOrEqualTo(String value) {
            addCriterion("ICON_CSS <=", value, "iconCss");
            return (Criteria) this;
        }

        public Criteria andIconCssLike(String value) {
            addCriterion("ICON_CSS like", value, "iconCss");
            return (Criteria) this;
        }

        public Criteria andIconCssNotLike(String value) {
            addCriterion("ICON_CSS not like", value, "iconCss");
            return (Criteria) this;
        }

        public Criteria andIconCssIn(List<String> values) {
            addCriterion("ICON_CSS in", values, "iconCss");
            return (Criteria) this;
        }

        public Criteria andIconCssNotIn(List<String> values) {
            addCriterion("ICON_CSS not in", values, "iconCss");
            return (Criteria) this;
        }

        public Criteria andIconCssBetween(String value1, String value2) {
            addCriterion("ICON_CSS between", value1, value2, "iconCss");
            return (Criteria) this;
        }

        public Criteria andIconCssNotBetween(String value1, String value2) {
            addCriterion("ICON_CSS not between", value1, value2, "iconCss");
            return (Criteria) this;
        }

        public Criteria andInformationIsNull() {
            addCriterion("INFORMATION is null");
            return (Criteria) this;
        }

        public Criteria andInformationIsNotNull() {
            addCriterion("INFORMATION is not null");
            return (Criteria) this;
        }

        public Criteria andInformationEqualTo(String value) {
            addCriterion("INFORMATION =", value, "information");
            return (Criteria) this;
        }

        public Criteria andInformationNotEqualTo(String value) {
            addCriterion("INFORMATION <>", value, "information");
            return (Criteria) this;
        }

        public Criteria andInformationGreaterThan(String value) {
            addCriterion("INFORMATION >", value, "information");
            return (Criteria) this;
        }

        public Criteria andInformationGreaterThanOrEqualTo(String value) {
            addCriterion("INFORMATION >=", value, "information");
            return (Criteria) this;
        }

        public Criteria andInformationLessThan(String value) {
            addCriterion("INFORMATION <", value, "information");
            return (Criteria) this;
        }

        public Criteria andInformationLessThanOrEqualTo(String value) {
            addCriterion("INFORMATION <=", value, "information");
            return (Criteria) this;
        }

        public Criteria andInformationLike(String value) {
            addCriterion("INFORMATION like", value, "information");
            return (Criteria) this;
        }

        public Criteria andInformationNotLike(String value) {
            addCriterion("INFORMATION not like", value, "information");
            return (Criteria) this;
        }

        public Criteria andInformationIn(List<String> values) {
            addCriterion("INFORMATION in", values, "information");
            return (Criteria) this;
        }

        public Criteria andInformationNotIn(List<String> values) {
            addCriterion("INFORMATION not in", values, "information");
            return (Criteria) this;
        }

        public Criteria andInformationBetween(String value1, String value2) {
            addCriterion("INFORMATION between", value1, value2, "information");
            return (Criteria) this;
        }

        public Criteria andInformationNotBetween(String value1, String value2) {
            addCriterion("INFORMATION not between", value1, value2, "information");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BASE_MODULES
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 10 11:28:31 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BASE_MODULES
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}