package com.whty.euicc.base.pojo;

public class BaseRoles {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_ROLES.ROLE_ID
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_ROLES.ROLE_NAME
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_ROLES.ROLE_DESC
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    private String roleDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_ROLES.ROLE_ID
     *
     * @return the value of BASE_ROLES.ROLE_ID
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_ROLES.ROLE_ID
     *
     * @param roleId the value for BASE_ROLES.ROLE_ID
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_ROLES.ROLE_NAME
     *
     * @return the value of BASE_ROLES.ROLE_NAME
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_ROLES.ROLE_NAME
     *
     * @param roleName the value for BASE_ROLES.ROLE_NAME
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_ROLES.ROLE_DESC
     *
     * @return the value of BASE_ROLES.ROLE_DESC
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_ROLES.ROLE_DESC
     *
     * @param roleDesc the value for BASE_ROLES.ROLE_DESC
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }
}