package com.whty.euicc.base.dao;

import org.apache.ibatis.annotations.Param;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;
import com.whty.euicc.base.pojo.BaseUserRoleExample;
import com.whty.euicc.base.pojo.BaseUserRoleKey;

public interface BaseUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_USER_ROLE
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    int countByExample(BaseUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_USER_ROLE
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    int deleteByExample(BaseUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_USER_ROLE
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    int deleteByPrimaryKey(BaseUserRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_USER_ROLE
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    int insert(BaseUserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_USER_ROLE
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    int insertSelective(BaseUserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_USER_ROLE
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    PageList<BaseUserRoleKey> selectByExample(BaseUserRoleExample example, PageBounds pageBounds);
    
    
    PageList<BaseUserRoleKey> selectByExample(BaseUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_USER_ROLE
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    int updateByExampleSelective(@Param("record") BaseUserRoleKey record, @Param("example") BaseUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_USER_ROLE
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    int updateByExample(@Param("record") BaseUserRoleKey record, @Param("example") BaseUserRoleExample example);
}