package com.whty.euicc.base.dao;

import org.apache.ibatis.annotations.Param;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;
import com.whty.euicc.base.pojo.BaseRoles;
import com.whty.euicc.base.pojo.BaseRolesExample;

public interface BaseRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_ROLES
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    int countByExample(BaseRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_ROLES
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    int deleteByExample(BaseRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_ROLES
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_ROLES
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    int insert(BaseRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_ROLES
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    int insertSelective(BaseRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_ROLES
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    PageList<BaseRoles> selectByExample(BaseRolesExample example, PageBounds pageBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_ROLES
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    BaseRoles selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_ROLES
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    int updateByExampleSelective(@Param("record") BaseRoles record, @Param("example") BaseRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_ROLES
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    int updateByExample(@Param("record") BaseRoles record, @Param("example") BaseRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_ROLES
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    int updateByPrimaryKeySelective(BaseRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_ROLES
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    int updateByPrimaryKey(BaseRoles record);
}