pe-GFSTEList ProfileElement ::= header : {

  major-version 2,
  minor-version 0,
  profileType "SIMalliance Profile Package",
  iccid '89860110611108096225'H, 
  eUICC-Mandatory-services {
    usim NULL,
    milenage NULL,
    javacard NULL
  },
  eUICC-Mandatory-GFSTEList {     
  }
}
pe-gfm ProfileElement ::= genericFileManagement : {
  gfm-header {
    mandated NULL,
    identification 1    
  },
  fileManagementCMD {
    {
      createFCP :{      	   
      	fileDescriptor '7821'H,
        fileID '3F00'H,       
        securityAttributesReferenced '0c'H,
        pinStatusTemplateDO '01020A'H
      },
      createFCP :{
      	fileDescriptor '4121'H,    
        fileID '2F05'H,
        securityAttributesReferenced '07'H,
        efFileSize '04'H,
      },
      createFCP :{
      	fileDescriptor '4121'H,
        fileID '2FE2'H,
        securityAttributesReferenced '08'H,
        efFileSize '0A'H
      },
      fillFileContent : '98681001161180902652'H,
      createFCP :{
      	fileDescriptor '42210020'H,
        fileID '2F00'H,
        securityAttributesReferenced '08'H,
        efFileSize '0020'H,
      },
      fillFileContent : '611D4F10A0000000871002FF86FFFF89FFFFFFFF5009556E6976657253494DFF'H,
      createFCP :{
      	fileDescriptor '4221002f'H,
        fileID '2F06'H,
        securityAttributesReferenced '08'H,
        efFileSize '0234'H
      },
    fillFileContent : '80011bA406830101950108'H,
    fillFileOffset : 36,
    fillFileContent : '80011bA406830101950108840132A406830101950108'H,   	
    fillFileOffset : 25
    fillFileContent : '800103A406830101950108800118A406830102950108'H,
    fillFileOffset : 25
    fillFileContent : '800101A406830101950108800102A406830102950108800118A40683010A950108'H,
    fillFileOffset : 14
    fillFileContent : '800103A406830101950108800118A40683010A950108'H,
    fillFileOffset : 25
    fillFileContent : '800101A40683010195010880011AA40683010A950108'H,
    fillFileOffset : 25
    fillFileContent : '8001019000800102A406830101950108800118A40683010A950108'H,
    fillFileOffset : 20
    fillFileContent : '800101900080011AA40683010a950108'H,
    fillFileOffset : 31
    fillFileContent : '800111A40683010195010880010AA40683010A950108'H,   
    fillFileOffset : 25    
    fillFileContent : '800101A406830101950108800102A406830102950108840132A406830101950108800118A40683010A950108'H,
    fillFileOffset : 3    
    fillFileContent : '800113A406830101950108800108A40683010A950108'H,   
    fillFileOffset : 25 
    fillFileContent : '80011BA40683010A950108'H,    
      }
    }
  }
  pukVal ProfileElement ::= pukCodes : { 
  puk-Header { 
    mandated NULL, 
    identification 2 
  }, 
  pukCodes { 
		{ 
			keyReference pukAppl1, 
			pukValue '3238353634333833'H, 
			maxNumOfAttemps-retryNumLeft 153 
		}, 
		{ 
			keyReference pukAppl2, 
			pukValue '3437383937383736'H 
		}
	} 
} 
pe-pincodes0 ProfileElement ::= pinCodes : {
  pin-Header {
    mandated NULL,
    identification 3
  },
  pinCodes pinconfig : {
    {
      keyReference pinAppl1,
      pinValue '31323334FFFFFFFF'H,
      unblockingPINReference pukAppl1,
    },
    {
      keyReference pinAppl2,
      pinValue '3635353032303332'H,
      unblockingPINReference pukAppl2
    },
    {
      keyReference adm1,
      pinValue '3334383a3c37343e'H,
    }
  }
}
usim-val ProfileElement ::= genericFileManagement : {
  usim-header {
    mandated NULL,
    identification 4
  },
  fileManagementCMD {
  {
   createFCP :{
     	fileDescriptor '7821'H,     
      fileID '7FF0'H,
      dfName 'A0000000871002FF86FFff89ffffffff'H,
      securityAttributesReferenced '0c'H,           
      pinStatusTemplateDO '01810A'H
  },
   createFCP :{
     	fileDescriptor '4121'H,     
      fileID '6f07'H,
      securityAttributesReferenced '06'H,
      efFileSize '09'H,  
      shortEFID '38'H, 
      fillFileContent : '0832141049737856F6'H
  },
   createFCP :{
     	fileDescriptor '4221002f'H,     
      fileID '6f06'H,
      securityAttributesReferenced '08'H,
      efFileSize '0234'H,  
      shortEFID 'b8'H
    },
    fillFileContent : '80011bA406830101950108'H,
    fillFileOffset : 36,
    fillFileContent : '80011bA406830101950108840132A406830101950108'H,
    fillFileOffset : 25,
    fillFileContent : '800103A406830101950108800118A406830102950108'H,
    fillFileOffset : 25,
    fillFileContent : '800101A406830101950108800102A406830102950108800118A40683010A950108'H,
    fillFileOffset : 14,
    fillFileContent : '800103A406830101950108800118A40683010A950108'H,
    fillFileOffset : 25,
    fillFileContent : '800101A40683010195010880011AA40683010A950108'H,
    fillFileOffset : 25,
    fillFileContent : '8001019000800102A406830101950108800118A40683010A950108'H,
    fillFileOffset : 20,
    fillFileContent : '800101900080011AA40683010a950108'H,
    fillFileOffset : 31,
    fillFileContent : '800111A40683010195010880010AA40683010A950108'H,   
    fillFileOffset : 25,  
    fillFileContent : '800101A406830101950108800102A406830102950108840132A406830101950108800118A40683010A950108'H,
    fillFileOffset : 3,  
    fillFileContent : '800113A406830101950108800108A40683010A950108'H,  
    fillFileOffset : 25,
    fillFileContent : '80011BA40683010A950108'H,    
 createFCP :{
     	fileDescriptor '4121'H,     
      fileID '6f08'H,
      securityAttributesReferenced '05'H,
      efFileSize '21'H,  
      shortEFID '40'H,
      proprietaryEFInfo {  
      fillPattern '07FF'H 
      }
    },
 createFCP :{
      fileDescriptor '4121'H,         
      fileID '6f09'H,
      securityAttributesReferenced '05'H,
      efFileSize '21'H,  
      shortEFID '48'H
    },
    fillFileContent : '07FFffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff'H,
    createFCP :{
     	fileDescriptor '4121'H,       
      fileID '6f31'H,
      securityAttributesReferenced '06'H,
      efFileSize '01'H,  
      shortEFID '90'H
      },
  createFCP :{
     	fileDescriptor '4121'H,    
      fileID '6f38'H,
      securityAttributesReferenced '02'H,
      efFileSize '0a'H,  
      shortEFID '20'H
    },
    fillFileContent : '9effbffdff3edc034001'H,
    createFCP :{
     	fileDescriptor '4121'H,      
      fileID '6f46'H,
      securityAttributesReferenced '0A'H,
      efFileSize '11'H,
      proprietaryEFInfo { 
      fillPattern '00'H 
      }      
    },
  createFCP :{
     	fileDescriptor '4121'H,     
      fileID '6f78'H,
      securityAttributesReferenced '06'H,
      efFileSize '02'H,  
      shortEFID '30'H
    },
    fillFileContent : '0000'H,
    createFCP :{
     	fileDescriptor '4121'H,     
      fileID '6f7b'H,
      securityAttributesReferenced '05'H,
      efFileSize '1e'H
    },
    fillFileContent : '64F00064F02064F04064F07064F08064F03064F011FFFFFFFFFFFFFFFFFF'H,
    createFCP :{
      fileDescriptor '4121'H,      
      fileID '6f7e'H,
      securityAttributesReferenced '05'H,
      efFileSize '0b'H,  
      shortEFID '58'H
    },
    fillFileContent : 'FFFFFFFFFFFFFFFFFEFF01'H,
   createFCP :{
     	fileDescriptor '4121'H,       
      fileID '6fad'H,
      securityAttributesReferenced '08'H,
      efFileSize '04'H,  
      shortEFID '18'H
    },
    fillFileContent : '00000002'H,
   createFCP :{
      fileDescriptor '42210014'H,
      fileID '6fb7'H,
      securityAttributesReferenced '08'H,
      efFileSize '50'H,  
      shortEFID '08'H
    },    
    createFCP :{
     	fileDescriptor '4121'H,  
      fileID '6fc4'H,
      securityAttributesReferenced '05'H,
      efFileSize '32'H
    }, 
  createFCP :{
     	fileDescriptor '4121'H,
      fileID '6f73'H,
      securityAttributesReferenced '05'H,
      efFileSize '0e'H,  
      shortEFID '60'H
    },
    fillFileContent : 'FFFFFFFFFFFFFFFFFFFFFFFEFF01'H,
 createFCP :{
      fileDescriptor '4221001c'H,
      fileID '6f3b'H,
      securityAttributesReferenced '04'H,
      efFileSize '0118'H
    },
 createFCP :{
      fileDescriptor '422100b0'H,
      fileID '6f3c'H,
      securityAttributesReferenced '05'H,
      efFileSize '2260'H,
      proprietaryEFInfo { 
      fillPattern '00FF'H 
      }
    },
 createFCP :{
    	fileDescriptor '42210028'H,     
      fileID '6f42'H,
      securityAttributesReferenced '05'H,
      efFileSize 'c8'H
    },   
   createFCP :{
      fileDescriptor '4121'H,  
      fileID '6f43'H,
      securityAttributesReferenced '05'H,
      efFileSize '02'H    
  },
 createFCP :{
     	fileDescriptor '4121'H, 
      fileID '6f56'H,
      securityAttributesReferenced '04'H,
      efFileSize '01'H,  
      shortEFID '28'H
    },
    fillFileContent : '00'H
   createFCP :{
     	fileDescriptor '4121'H,      
      fileID '6f5c'H,
      securityAttributesReferenced '06'H,
      efFileSize '03'H,  
      shortEFID '80'H
    }, 
  createFCP :{
     	fileDescriptor '4121'H,     
      fileID '6f5b'H,
      securityAttributesReferenced '05'H,
      efFileSize '06'H,  
      shortEFID '78'H
    },
    fillFileContent : 'f00000f00000'H
}
}
}
 pe-opt-usim ProfileElement ::= genericFileManagement : {
  OPT-USIM-header {
    mandated NULL,
    identification 5
  },
fileManagementCMD {
  {
  createFCP :{
      fileDescriptor '4121'H,     
      fileID '6f05'H,
      securityAttributesReferenced '07'H,
      efFileSize '04'H,  
      shortEFID '10'H
    },
       fillFileContent : '7A68656E'H,
  createFCP :{
      fileDescriptor '4121'H,     
      fileID '6f60'H,
      securityAttributesReferenced '05'H,
      efFileSize '28'H,  
      shortEFID '50'H
    },
    fillFileContent : '64F010400064F090400064F010800064F0908000FFFFFF0000FFFFFF0000FFFFFF0000FFFFFF0000'H,
  createFCP :{
      fileDescriptor '4121'H,     
      fileID '6f37'H,
      securityAttributesReferenced '04'H,
      efFileSize '03'H  
      },
      fillFileContent : '000000'H,
 createFCP :{
      fileDescriptor '46210003'H,     
      fileID '6f39'H,
      securityAttributesReferenced '0a'H,
      efFileSize '3c'H,  
      shortEFID 'e0'H,
      proprietaryEFInfo { 
      fillPattern '00'H
      	 }
    },
   createFCP :{
      fileDescriptor '4121'H,     
      fileID '6f3e'H,
      securityAttributesReferenced '06'H,
      efFileSize '01'H  
      },
   createFCP :{
     	fileDescriptor '4121'H,
      fileID '6f3f'H,
      securityAttributesReferenced '06'H,
      efFileSize '01'H  
      },
   createFCP :{
     	fileDescriptor '4121'H,     
      fileID '6f41'H,
      securityAttributesReferenced '04'H,
      efFileSize '05'H     
    },
    fillFileContent : 'ffffff0000'H
    createFCP :{
      fileDescriptor '4121'H,     
      fileID '6f45'H,
      securityAttributesReferenced '05'H,
      efFileSize '14'H        
    },
    createFCP :{
     	fileDescriptor '4121'H,     
      fileID '6f48'H,
      securityAttributesReferenced '06'H,
      efFileSize '14'H,  
      shortEFID '70'H
    },
    createFCP :{
      fileDescriptor '4121'H,     
      fileID '6f50'H,
      securityAttributesReferenced '05'H,
      efFileSize '20'H
    },
   createFCP :{
      fileDescriptor '4221001c'H,
      fileID '6f40'H,
      securityAttributesReferenced '05'H,
      efFileSize '38'H
    },   
   createFCP :{
     	fileDescriptor '42210018'H,     
      fileID '6f49'H,
      securityAttributesReferenced '06'H,
      efFileSize 'f0'H
    },
    createFCP :{
      fileDescriptor '4221000d'H,     
      fileID '6f4b'H,
      securityAttributesReferenced '04'H,
      efFileSize '27'H,
     proprietaryEFInfo {
       fillPattern '00FF'H
      	 }
    },
    createFCP :{
      fileDescriptor '4221000d'H,     
      fileID '6f4c'H,
      securityAttributesReferenced '06'H,
      efFileSize '41'H
      proprietaryEFInfo {
        fillPattern '00FF'H
       	 }
    },
   createFCP :{
      fileDescriptor '42210014'H,     
      fileID '6f47'H,
      securityAttributesReferenced '05'H,
      efFileSize '05dc'H
       proprietaryEFInfo {
       fillPattern '00FF'H
      	 }
    },
    createFCP :{
      	fileDescriptor '46210028'H,    
      fileID '6f80'H,
      securityAttributesReferenced '05'H,
      efFileSize '0320'H,        
      shortEFID 'a0'H
        proprietaryEFInfo {
       fillPattern 'FF'H
      	 }
    },
    fillFileOffset : 21, 
    fillFileContent : '0000000000'H,
     createFCP :{
      fileDescriptor '46210027'H,      
      fileID '6f81'H,
      securityAttributesReferenced '05'H,
      efFileSize '030c'H,  
      shortEFID 'a8'H
       proprietaryEFInfo { 
      fillPattern 'FF'H
      	 }
    },
    fillFileOffset : 21,     
    fillFileContent : '00000000'H,
     createFCP :{
     	fileDescriptor '46210003'H,     
      fileID '6f82'H,
      securityAttributesReferenced '0a'H,
      efFileSize '03'H
    },
    fillFileContent : '000000'H,
  createFCP :{
      fileDescriptor '46210003'H,     
      fileID '6f83'H,
      securityAttributesReferenced '0a'H,
      efFileSize '03'H
    },
    fillFileContent : '000000'H,
    createFCP :{
      fileDescriptor '4221000d'H,     
      fileID '6f4e'H,
      securityAttributesReferenced '05'H,
      efFileSize '41'H
      proprietaryEFInfo {
          fillPattern '00FF'H
      	 }
    },
    createFCP :{
      fileDescriptor '4221000f'H,     
      fileID '6f4f'H,
      securityAttributesReferenced '05'H,
      efFileSize '4b'H,  
      shortEFID 'b0'H
      },
     createFCP :{
      	fileDescriptor '4121'H,
      fileID '6fb6'H,
      securityAttributesReferenced '05'H,
      efFileSize '01'H
    },
    fillFileContent : '00'H,
    createFCP :{
      fileDescriptor '4121'H,     
      fileID '6fc3'H,
      securityAttributesReferenced '05'H,
      efFileSize '04'H
    },
    createFCP :{
     	fileDescriptor '4121'H,     
      fileID '6f57'H,
      securityAttributesReferenced '04'H,
      efFileSize 'c8'H,
      proprietaryEFInfo { 
       fillPattern '00ff'H 
       }
    },
    createFCP :{
     	fileDescriptor '4121'H,     
      fileID '6f2c'H,
      securityAttributesReferenced '05'H,
      efFileSize '10'H
    },
   createFCP :{
      fileDescriptor '4121'H,     
      fileID '6f32'H,
      securityAttributesReferenced '06'H,
      efFileSize '06'H
     },
    createFCP :{
      fileDescriptor '4121'H,     
      fileID '6f61'H,
      securityAttributesReferenced '06'H,
      efFileSize '01f4'H,  
      shortEFID '88'H,
      proprietaryEFInfo {
      repeatPattern 'FFFFFF0000'H 
      }
    },
    fillFileContent : '64F010400064F090400064F010800064F0908000'H,
    createFCP :{
      fileDescriptor '4121'H,     
      fileID '6f62'H,
      securityAttributesReferenced '06'H,
      efFileSize '28'H,  
      shortEFID '98'H
    },
    fillFileContent : '64F010400064F090400064F010800064F0908000FFFFFF0000FFFFFF0000FFFFFF0000FFFFFF0000'H,
    createFCP :{
     	fileDescriptor '4221000e'H,      
      fileID '6fc5'H,
      securityAttributesReferenced '08'H,
      efFileSize '70'H,  
      shortEFID 'c8'H
    },   
    createFCP :{
      fileDescriptor '42210008'H,     
      fileID '6fc6'H,
      securityAttributesReferenced '08'H,
      efFileSize '40'H,  
      shortEFID 'd0'H
    },    
    createFCP :{
      fileDescriptor '42210004'H,     
      fileID '6fce'H,
      securityAttributesReferenced '05'H,
      efFileSize '04'H
    },
    fillFileContent : '000000ff'H,
  createFCP :{
      fileDescriptor '4121'H,     
      fileID '6fd0'H,
      securityAttributesReferenced '06'H,
      efFileSize '17'H
    },    
   createFCP :{
      fileDescriptor '4221000d'H,     
      fileID '6fd1'H,
      securityAttributesReferenced '05'H,
      efFileSize '0d'H
    },
   createFCP :{
      fileDescriptor '4121'H,     
      fileID '6fd2'H,
      securityAttributesReferenced '04'H,
      efFileSize '17'H
   }, 
   createFCP :{
      fileDescriptor '42210011'H,     
      fileID '6fd3'H,
      securityAttributesReferenced '06'H,
      efFileSize '4b'H
    },
   createFCP :{
      fileDescriptor '4121'H,     
      fileID '6fb3'H,
      securityAttributesReferenced '06'H,
      efFileSize '04'H
     }, 
   createFCP :{
      fileDescriptor '4121'H,     
      fileID '6fb4'H,
      securityAttributesReferenced '06'H,
      efFileSize '07'H
    },
    fillFileContent : '000000000000fc'H, 
   createFCP :{
      fileDescriptor '4121'H,     
      fileID '6fb5'H,
      securityAttributesReferenced '06'H,
      efFileSize '02'H
    },
    fillFileContent : '0000'H, 
   createFCP :{
      fileDescriptor '4121'H,     
      fileID '6fd9'H,
      securityAttributesReferenced '06'H,
      efFileSize '0c'H,
      proprietaryEFInfo {
       fillPattern '64f010ff'H 
       }
     },
   createFCP :{
      fileDescriptor '4121'H,     
      fileID '6fdb'H,
      securityAttributesReferenced '06'H,
      efFileSize '01'H
    },
    fillFileContent : '02'H
  }
  }
  } 
  pe-akaParameter ProfileElement ::= akaParameter : {
  aka-header {
    mandated NULL,
    identification 8
  },
  algoConfiguration algoParameter : {
  algorithmID milenage,
  algorithmOptions '01'H,
  key '7EB661D5D8F6C86E539881B8955AA1CD'H,
  opc '0A00B86C53BFDE29B1092124AAF093E7'H,
  authCounterMax '010203'H 
  },
}
pe-sd ProfileElement ::= securityDomain : {
  sd-Header {
    mandated NULL,
    identification 9
  },
 instance { 
 	  applicationLoadPackageAID 'A0000001515350'H,
 	  classAID 'A000000151535041'H,
 	  instanceAID 'A000000151000000'H, 
 	  applicationPrivileges '82FC80'H, 
     lifeCycleState '0F'H, 
     applicationSpecificParametersC9 '810203708102025581028000'H, 
     applicationParameters { 
     uiccToolkitApplicationSpecificParametersField '0100000100000002011203B2010000'H 
     } 
     }, 
     keyList {      
       { 
         keyUsageQualifier '38'H, 
         keyAccess '00'H, 
         keyIdentifier '01'H, 
         keyVersionNumber '01'H, 
         keyCompontents { 
           { 
           keyType '80'H, 
           keyData 'D9BE655005BEB775324D53DEA699F13A'H 
           } 
         } 
       }, 
       { 
          keyUsageQualifier '34'H, 
          keyAccess '00'H, 
          keyIdentifier '02'H, 
          keyVersionNumber '01'H, 
          keyCompontents { 
             { 
             keyType '80'H, 
             keyData '52DABF691AFD0E2B540CA6A09DEE3BF9'H 
             } 
           } 
        }, 
        { 
         keyUsageQualifier 'C8'H, 
         keyAccess '00'H, 
         keyIdentifier '03'H, 
         keyVersionNumber '01'H, 
         keyCompontents {
            { 
            keyType '80'H, 
            keyData 'F75D1211F09D3BD5DEB5C3726C5C71E9'H 
            } 
          } 
       }
       { 
           keyUsageQualifier '38'H, 
           keyAccess '00'H, 
           keyIdentifier '01'H, 
           keyVersionNumber '02'H, 
           keyCompontents {
             { 
             keyType '80'H, 
             keyData '31580DB9C617ED485FD9B309123BA2EC'H 
             } 
            } 
        }, 
       { 
        keyUsageQualifier '34'H, 
          keyAccess '00'H, 
          keyIdentifier '02'H, 
          keyVersionNumber '02'H, 
          keyCompontents {
             { 
             keyType '80'H, 
             keyData 'AEB60E98703B6C8B343DAEFC2EE64099'H 
             } 
          } 
        }, 
        { 
          keyUsageQualifier 'C8'H, 
          keyAccess '00'H, 
          keyIdentifier '03'H, 
          keyVersionNumber '02'H, 
          keyCompontents {
              { 
              keyType '80'H, 
              keyData 'AB1F22EBB0C85708A531BDE6758782F4'H 
              } 
          } 
         },
        { 
              keyUsageQualifier '38'H, 
              keyAccess '00'H, 
              keyIdentifier '01'H, 
              keyVersionNumber '03'H, 
              keyCompontents {
                { 
                keyType '80'H, 
                keyData '5B65D650F410BE5435D26BC7778AA4F1'H 
                } 
              } 
          }, 
         { 
           keyUsageQualifier '34'H, 
           keyAccess '00'H, 
           keyIdentifier '02'H, 
           keyVersionNumber '03'H, 
           keyCompontents {
               { 
               keyType '80'H, 
               keyData 'EF99C2514486B864AE2943DAD7929895'H 
               } 
           } 
        }, 
        { 
           keyUsageQualifier 'C8'H, 
           keyAccess '00'H, 
           keyIdentifier '03'H, 
           keyVersionNumber '03'H, 
           keyCompontents {
               { 
               keyType '80'H, 
               keyData 'C53210DB6B300F790A998C81D2F0B42C'H 
                } 
              } 
          }
          { 
           keyUsageQualifier '38'H, 
           keyAccess '00'H, 
           keyIdentifier '01'H, 
           keyVersionNumber '04'H, 
           keyCompontents {
               { 
               keyType '80'H, 
               keyData 'B4589C2516A245AD77A1226064AC55DE'H 
               } 
           } 
        }, 
        { 
           keyUsageQualifier '34'H, 
           keyAccess '00'H, 
           keyIdentifier '02'H, 
           keyVersionNumber '04'H, 
           keyCompontents {
               { 
               keyType '80'H, 
               keyData 'BF594DEF53715FABF53283546B0AE90F'H 
               } 
           } 
        }, 
        { 
           keyUsageQualifier 'C8'H, 
           keyAccess '00'H, 
           keyIdentifier '03'H, 
           keyVersionNumber '04'H, 
           keyCompontents {
               { 
               keyType '80'H, 
               keyData '3F4C3E7FE147FE15C8F170D7DB8FBFFD'H 
               } 
              } 
          }
          { 
           keyUsageQualifier '38'H, 
           keyAccess '00'H, 
           keyIdentifier '01'H, 
           keyVersionNumber '20'H, 
           keyCompontents {
               { 
               keyType '80'H, 
               keyData 'AEA57E0042780CEBBBD7CA2FE63CFF05'H 
               } 
           } 
        }, 
        { 
           keyUsageQualifier '34'H, 
           keyAccess '00'H, 
           keyIdentifier '02'H, 
           keyVersionNumber '20'H, 
           keyCompontents {
               { 
               keyType '80'H, 
               keyData '888D0508C5AF62E085F7D3FB713DBA33'H 
               } 
           } 
        }, 
        { 
           keyUsageQualifier 'C8'H, 
           keyAccess '00'H, 
           keyIdentifier '03'H, 
           keyVersionNumber '20'H, 
           keyCompontents {
               { 
               keyType '80'H, 
               keyData '42C9F4D5271376425FC49D5C7E697CA0'H 
               } 
              } 
          }
          { 
           keyUsageQualifier '38'H, 
           keyAccess '00'H, 
           keyIdentifier '01'H, 
           keyVersionNumber '21'H, 
           keyCompontents {
              { 
               keyType '80'H, 
               keyData '7DAD857600BB69B4FB06CF5CA4FE54DE'H 
               } 
           } 
        }, 
        { 
           keyUsageQualifier '34'H, 
           keyAccess '00'H, 
           keyIdentifier '02'H, 
           keyVersionNumber '21'H, 
           keyCompontents {
               { 
               keyType '80'H, 
               keyData '9E14F922D048778280CD6D347BE229E1'H 
               } 
           } 
        }, 
        { 
           keyUsageQualifier 'C8'H, 
           keyAccess '00'H, 
           keyIdentifier '03'H, 
           keyVersionNumber '21'H, 
           keyCompontents {
              { 
               keyType '80'H, 
               keyData '8042F9DA6A8E6EACB81689ABEC2E1979'H 
                } 
           } 
       }
         { 
           keyUsageQualifier '38'H, 
           keyAccess '00'H, 
           keyIdentifier '01'H, 
           keyVersionNumber '22'H, 
           keyCompontents {
               { 
               keyType '80'H, 
               keyData '27B02F2D73EE20CCBF4E47D006C85F7B'H 
               } 
           } 
        }, 
        { 
           keyUsageQualifier '34'H, 
           keyAccess '00'H, 
           keyIdentifier '02'H, 
           keyVersionNumber '22'H, 
           keyCompontents {
               { 
               keyType '80'H, 
               keyData '9995ED0E5C8A45EFC8DB05759F12701F'H 
               } 
           } 
        }, 
        { 
           keyUsageQualifier 'C8'H, 
           keyAccess '00'H, 
           keyIdentifier '03'H, 
           keyVersionNumber '22'H, 
           keyCompontents {
               { 
               keyType '80'H, 
               keyData '62ACBF1B43BBD26E40A93782FEDAA08E'H 
                } 
              } 
          },
         { 
             keyUsageQualifier '38'H, 
             keyAccess '00'H, 
             keyIdentifier '01'H, 
             keyVersionNumber '23'H, 
             keyCompontents { 
             { 
             keyType '80'H, 
             keyData 'A8C5D6EF424980B9B0F2E762E22CAD9C'H 
             } 
             } 
             }, 
             { 
             keyUsageQualifier '34'H, 
             keyAccess '00'H, 
             keyIdentifier '02'H, 
             keyVersionNumber '23'H, 
             keyCompontents { 
             { 
             keyType '80'H, 
             keyData '407DB4AEFC58BA7C490097BB60199204'H 
             } 
             } 
             }, 
             { 
             keyUsageQualifier 'C8'H, 
             keyAccess '00'H, 
             keyIdentifier '03'H, 
             keyVersionNumber '23'H, 
             keyCompontents { 
             { 
             keyType '80'H, 
             keyData 'F67B1FB523C6D7FFAD1B8532BAEFBA85'H 
                  } 
                } 
               }
        { 
           keyUsageQualifier '38'H, 
           keyAccess '00'H, 
           keyIdentifier '01'H, 
           keyVersionNumber '31'H, 
           keyCompontents {
               { 
               keyType '88'H, 
               keyData '11010203040506070809101112131415'H 
               } 
           } 
        }, 
        { 
           keyUsageQualifier '34'H, 
           keyAccess '00'H, 
           keyIdentifier '02'H, 
           keyVersionNumber '31'H, 
           keyCompontents {
               { 
               keyType '88'H, 
               keyData '11020304050607080910111213141501'H 
               } 
           } 
        }, 
         { 
        keyUsageQualifier 'C8'H, 
        keyAccess '00'H, 
        keyIdentifier '03'H, 
        keyVersionNumber '31'H, 
        keyCompontents {
            { 
            keyType '88'H, 
            keyData '11030405060708091011121314150102'H 
            } 
           } 
          }
        { 
           keyUsageQualifier '38'H, 
           keyAccess '00'H, 
           keyIdentifier '01'H, 
           keyVersionNumber '32'H, 
           keyCompontents {
               { 
               keyType '88'H, 
               keyData '12010203040506070809101112131415'H 
               } 
           } 
        }, 
        { 
           keyUsageQualifier '34'H, 
           keyAccess '00'H, 
           keyIdentifier '02'H, 
           keyVersionNumber '32'H, 
           keyCompontents {
               { 
               keyType '88'H, 
               keyData '12020304050607080910111213141501'H 
               } 
           } 
        }, 
         { 
        keyUsageQualifier 'C8'H, 
        keyAccess '00'H, 
        keyIdentifier '03'H, 
        keyVersionNumber '32'H, 
        keyCompontents {
            { 
            keyType '88'H, 
            keyData '12030405060708091011121314150102'H 
            } 
           } 
          }
        { 
           keyUsageQualifier '38'H, 
           keyAccess '00'H, 
           keyIdentifier '01'H, 
           keyVersionNumber '33'H, 
           keyCompontents {
               { 
               keyType '88'H, 
               keyData '13010203040506070809101112131415'H 
               } 
           } 
        }, 
        { 
           keyUsageQualifier '34'H, 
           keyAccess '00'H, 
           keyIdentifier '02'H, 
           keyVersionNumber '33'H, 
           keyCompontents {
               { 
               keyType '88'H, 
               keyData '13020304050607080910111213141501'H 
               } 
           } 
        }, 
         { 
        keyUsageQualifier 'C8'H, 
        keyAccess '00'H, 
        keyIdentifier '03'H, 
        keyVersionNumber '33'H, 
        keyCompontents {
            { 
            keyType '88'H, 
            keyData '13030405060708091011121314150102'H 
            } 
           } 
          }
        { 
           keyUsageQualifier '38'H, 
           keyAccess '00'H, 
           keyIdentifier '01'H, 
           keyVersionNumber '34'H, 
           keyCompontents {
               { 
               keyType '88'H, 
               keyData '14010203040506070809101112131415'H 
               } 
           } 
        }, 
        { 
           keyUsageQualifier '34'H, 
           keyAccess '00'H, 
           keyIdentifier '02'H, 
           keyVersionNumber '34'H, 
           keyCompontents {
               { 
               keyType '88'H, 
               keyData '14020304050607080910111213141501'H 
               } 
           } 
        }, 
         { 
        keyUsageQualifier 'C8'H, 
        keyAccess '00'H, 
        keyIdentifier '03'H, 
        keyVersionNumber '34'H, 
        keyCompontents {
            { 
            keyType '88'H, 
            keyData '14030405060708091011121314150102'H 
            } 
           } 
          }
         } 
        } 
      }
pe-GSM-ACCESS ProfileElement ::= genericFileManagement : { 
gsm-access-header { 
mandated NULL, 
identification 6 
}, 
fileManagementCMD { 
 {
 filePath : '7ff0'H,
   createFCP : {
      fileDescriptor '7821'H,  
      fileID '5F3b'H,    
      securityAttributesReferenced '0c'H,
      pinStatusTemplateDO '01810A'H
    },
  createFCP : {
      fileDescriptor '4121'H,
      fileID '4f20'H,    
      securityAttributesReferenced '05'H,
      efFileSize '09'H,  
      shortEFID '08'H
    },
    fillFileContent : 'FFFFFFFFFFFFFFFF07'H,
 createFCP : {
      fileDescriptor '4121'H,
      fileID '4f52'H, 
      securityAttributesReferenced '05'H,
      efFileSize '09'H,  
      shortEFID '10'H
    },
    fillFileContent : 'FFFFFFFFFFFFFFFF07'H,
  createFCP : {
      fileDescriptor '4121'H,     
      fileID '4f63'H, 
      securityAttributesReferenced '05'H,
      efFileSize '0a'H
    },
 createFCP : {
      fileDescriptor '4121'H
      fileID '4f64'H, 
      securityAttributesReferenced '06'H,
      efFileSize '01'H      
    },
    fillFileContent : '00'H 
  }
}  
pe-rfmUicc ProfileElement ::= rfm : { 
 	rfm-header {
 	identification 10 
}, 
instanceAID 'A00000055910100001'H, 
tarList { 
'B00000'H 
}, 
minimumSecurityLevel '12'H, 
uiccAccessDomain '00'H, 
uiccAdminAccessDomain '00'H 
} 
pe-rfmUsim ProfileElement ::= rfm : {
  rfm-header { 
identification 11 
}, 
instanceAID 'A00000055910100002'H, 
tarList { 
'B00020'H 
}, 
minimumSecurityLevel '12'H, 
uiccAccessDomain '00'H, 
uiccAdminAccessDomain '00'H, 
adfRFMAccess { 
adfAID 'A0000000871002FF33FF018900000100'H, 
adfAccessDomain '02000100'H, 
adfAdminAccessDomain '02000100'H 
} 
}       
PE-telecom ProfileElement ::= genericFileManagement: {
 telecom-header {
    mandated NULL,
    identification 12
  },
  fileManagementCMD { 
  	{
  createFCP :{
      fileDescriptor '7821'H,     
      fileID '7f10'H,     
      securityAttributesReferenced '0c'H
      pinStatusTemplateDO '01810A'H
   },
   createFCP : {
   	    fileDescriptor '4221002f'H, 
        fileID '6F06'H,
        securityAttributesReferenced '08'H,
        shortEFID 'b8'H,
        linkPath '2F06'H
      },
 createFCP :{
      fileDescriptor '4121'H,        
    	fileID '6f20'H,  
      securityAttributesReferenced '01'H,
      efFileSize '09'H
    },
 createFCP :{
      fileDescriptor '46210003'H,     
     	fileID '6f21'H,  
      securityAttributesReferenced '02'H,
      efFileSize '0f'H
    },
  createFCP :{
      fileDescriptor '42210014'H,     
     	fileID '6f22'H,  
      securityAttributesReferenced '01'H,
      efFileSize '64'H
    },
   createFCP :{
     	fileDescriptor '4221001c'H,     
     	fileID '6f3a'H,  
      securityAttributesReferenced '03'H,
      efFileSize '0578'H
    },
  createFCP :{
      fileDescriptor '4221001c'H,         
    	fileID '6f3b'H,   
      securityAttributesReferenced '04'H,
      efFileSize '0118'H
     },
  createFCP :{
      fileDescriptor '422100b0'H,     
     	fileID '6f3c'H,  
      securityAttributesReferenced '05'H,
      efFileSize '0ed8'H,
      proprietaryEFInfo { 
      fillPattern '00FF'H 
      }
    },
 createFCP :{
     	fileDescriptor '4221001c'H,     
     	fileID '6f40'H,  
      securityAttributesReferenced '05'H,
      efFileSize '38'H
    },
  createFCP :{
      fileDescriptor '42210028'H,     
     	fileID '6f42'H,  
      securityAttributesReferenced '05'H,
      efFileSize 'c8'H
  },
    createFCP :{
      fileDescriptor '4121'H,     
     	fileID '6f43'H,  
      securityAttributesReferenced '05'H,
      efFileSize '02'H
    },
  createFCP :{
      fileDescriptor '4621001c'H,     
     	fileID '6f44 'H,  
      securityAttributesReferenced '05'H,
      efFileSize '0118'H
     },
  createFCP :{
     	fileDescriptor '4221001e'H,     
     	fileID '6f47'H,  
      securityAttributesReferenced '05'H,
      efFileSize '96'H,
      proprietaryEFInfo { 
      fillPattern '00FF'H 
      }
    },
  createFCP :{
      fileDescriptor '42210018'H,     
     	fileID '6f49'H,  
      securityAttributesReferenced '06'H,
      efFileSize 'f0'H,
    },
  createFCP :{
      fileDescriptor '4221000d'H,     
     	fileID '6f4a'H,  
      securityAttributesReferenced '05'H,
      efFileSize '5b'H,
      proprietaryEFInfo { 
      fillPattern '00FF'H 
      }
    },
    createFCP :{
      fileDescriptor '4221000d'H,     
     	fileID '6f4b'H,  
      securityAttributesReferenced '04'H,
      efFileSize '27'H,
      proprietaryEFInfo { 
      fillPattern '00FF'H 
      }
    },
 createFCP :{
     	fileDescriptor '4221000d'H,     
     	fileID '6f4c'H,  
      securityAttributesReferenced '06'H,
      efFileSize '41'H,
      proprietaryEFInfo {
       fillPattern '00FF'H
        }
    },
  createFCP :{
      fileDescriptor '4221000f'H,     
     	fileID '6f4f'H,  
      securityAttributesReferenced '05'H,
      efFileSize '4b'H
    },
  createFCP :{
      fileDescriptor '4121'H,     
     	fileID '6f54'H,  
      securityAttributesReferenced '06'H,
      efFileSize '17'H
    },
   filePath : '7f10'H,
    createFCP :{
      fileDescriptor '7821'H,     
      fileID '5f50'H,      
      securityAttributesReferenced '0c'H,
      pinStatusTemplateDO '01810A'H
    },
  createFCP :{
      fileDescriptor '4221000a'H,     
     	fileID '4f20'H,  
      securityAttributesReferenced '06'H,
      efFileSize '28'H,
      proprietaryEFInfo { 
      fillPattern '00FF'H 
      }
    },
  createFCP :{
      fileDescriptor '4121'H,     
     	fileID '4f21'H,  
      securityAttributesReferenced '06'H,
      efFileSize '0400'H 
  },
  createFCP :{
      fileDescriptor '4121'H,      
     	fileID '4f22'H,  
      securityAttributesReferenced '06'H,
      efFileSize '0400'H
    },
 createFCP :{
      fileDescriptor '4121'H,
     	fileID '4f23'H,  
      securityAttributesReferenced '06'H,
      efFileSize '0400'H
    },
 createFCP :{
      fileDescriptor '4121'H,
     	fileID '4f24'H,  
      securityAttributesReferenced '06'H,
      efFileSize '0400'H
    },
  filePath : '7f10'H,
  createFCP :{
      fileDescriptor '7821'H,     
      fileID '5f3a'H,      
      securityAttributesReferenced '0c'H,
      pinStatusTemplateDO '01810A'H
     },
  createFCP :{
      fileDescriptor '4221004c'H,     
      fileID '4f30'H, 
      securityAttributesReferenced '06'H,
      efFileSize '4c'H
    },
    fillFileContent : 'A81EC0034F3919C4034F5A1aC6034F5106C5034F4107C9034F6101C1034F3105A905CA034F7111AA14C2034F4A0aC7034F4B0bC8034F4C0cCB034F4F0fFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF'H,
    createFCP :{
      fileDescriptor '4221000f'H,     
      fileID '4f4f'H, 
      securityAttributesReferenced '05'H,
      efFileSize '41'H,
      shortEFID '78'H
    },
   createFCP :{
      fileDescriptor '4121'H,     
      fileID '4f22'H, 
      securityAttributesReferenced '05'H,
      efFileSize '04'H     
    },
    fillFileContent : '00000000'H,
   createFCP :{
      fileDescriptor '4121'H,     
      fileID '4f23'H, 
      securityAttributesReferenced '05'H,
      efFileSize '02'H
    },
    fillFileContent : '0000'H,
   createFCP :{
      fileDescriptor '4121'H,     
      fileID '4f24'H, 
      securityAttributesReferenced '05'H,
      efFileSize '02'H
    },
    fillFileContent : '0000'H,
   createFCP :{
      fileDescriptor '42210001'H,     
      fileID '4f31'H, 
      securityAttributesReferenced '05'H,
      efFileSize '32'H,
      shortEFID '28'H
    },
  createFCP :{
      fileDescriptor '4221001e'H,     
      fileID '4f39'H, 
      securityAttributesReferenced '05'H,
      efFileSize '0578'H,
      shortEFID 'c8 'H
    },
  createFCP :{
      fileDescriptor '4221000f'H,     
      fileID '4f5a'H, 
      securityAttributesReferenced '05'H,
      efFileSize '02ee'H,
      shortEFID 'd0 'H
    },
   createFCP :{
      fileDescriptor '42210004'H,     
      fileID '4f51'H, 
      securityAttributesReferenced '05'H,
      efFileSize 'c8'H,
      shortEFID '30'H
    },
    fillFileContent : '00000000'H,
    createFCP :{
      fileDescriptor '42210002'H,     
      fileID '4f61'H, 
      securityAttributesReferenced '05'H,
      efFileSize '64'H,
      shortEFID '08 'H
    },
    fillFileContent : '0000'H,
    createFCP :{
      fileDescriptor '42210002'H,     
      fileID '4f41'H, 
      securityAttributesReferenced '05'H,
      efFileSize '64'H,
      shortEFID '38 'H
    },
    fillFileContent : '0000'H,
    createFCP :{
     	fileDescriptor '42210028'H,     
      fileID '4f71'H, 
      securityAttributesReferenced '05'H,
      efFileSize 'c8'H,
      shortEFID '88 'H
    },
  createFCP :{
      fileDescriptor '42210018'H,     
      fileID '4f4c'H, 
      securityAttributesReferenced '05'H,
      efFileSize '60'H,
      shortEFID '60 'H
    },
   createFCP :{
      fileDescriptor '4221000d'H,
      fileID '4f4a'H, 
      securityAttributesReferenced '05'H,
      efFileSize '5b'H,
      shortEFID '50 'H,
      proprietaryEFInfo { 
      fillPattern '00FF'H 
      }
    },
 createFCP :{
      fileDescriptor '42210014'H,
      fileID '4f4b'H, 
      securityAttributesReferenced '05'H,
      efFileSize '28'H,
      shortEFID '58 'H,
      proprietaryEFInfo { 
      fillPattern '8075358bddFF'H 
      }     
    },   
  }
 }
}
pe-telectom ProfileElement ::= gsm-dcs1800: {
 telectom-header {
    mandated NULL,
    identification 14
  },
 fileManagementCMD { 
 	{
   createFCP :{
      fileDescriptor '7821'H,     
      fileID '7f20'H,
      securityAttributesReferenced '0c'H,
      pinStatusTemplateDO '01020A'H
    },
   createFCP : {
   	    fileDescriptor '4221002f'H, 
        fileID '6F06'H,
        securityAttributesReferenced '08'H,
        shortEFID 'b8'H,
        linkPath '2F06'H
      },
  createFCP :{
     	fileDescriptor '4121'H,
      fileID '6f05'H,
      securityAttributesReferenced '07'H,
      efFileSize '04'H
    },
 createFCP :{
      fileDescriptor '4121'H,
      fileID '6f07'H,
      securityAttributesReferenced '09'H,
      efFileSize '09'H
    },
    fillFileContent : '084906100113361574'H,  
  createFCP :{
     	fileDescriptor '4121'H,     
      fileID '6f20'H,
      securityAttributesReferenced '05'H,
      efFileSize '09'H
    },
    fillFileContent : 'ffffffffffffffff07'H,
  createFCP :{
     	fileDescriptor '4121'H,
      fileID '6f30'H,
      securityAttributesReferenced '05'H,
      efFileSize '012c'H,
      proprietaryEFInfo { 
      fillPattern '64f010'H 
      }
    },
   createFCP :{
      fileDescriptor '4121'H,     
      fileID '6f31'H,
      securityAttributesReferenced '06'H,
      efFileSize '01'H
    },
  createFCP :{
      fileDescriptor '4121'H,     
      fileID '6f37'H,
      securityAttributesReferenced '04'H,
      efFileSize '03'H
    },
    fillFileContent : '000000'H,
  createFCP :{
      fileDescriptor '4121'H,
      fileID '6f38'H,
      securityAttributesReferenced '06'H,
      efFileSize '0a'H
    },
    fillFileContent : 'ff33ffff3f003f03303c'H, 
  createFCP :{
      fileDescriptor '46210003'H,     
      fileID '6f39'H,
      securityAttributesReferenced '0a'H,
      efFileSize '3c'H
    },
    fillFileContent : '000000'H,
   createFCP :{
     	fileDescriptor '4121'H,
      fileID '6f3e'H,
      securityAttributesReferenced '06'H,
      efFileSize '01'H
    },
  createFCP :{
      fileDescriptor '4121'H,
      fileID '6f3f'H,
      securityAttributesReferenced '06'H,
      efFileSize '01'H
    },
  createFCP :{
     	fileDescriptor '4121'H,
      fileID '6f41'H,
      securityAttributesReferenced '04'H,
      efFileSize '05'H
    },
    fillFileContent : 'ffffff0000'H,
  createFCP :{
      fileDescriptor '4121'H,
      fileID '6f45'H,
      securityAttributesReferenced '05'H,
      efFileSize '14'H
    }
 createFCP :{
      fileDescriptor '4121'H,
      fileID '6f46'H,
      securityAttributesReferenced '08'H,
      efFileSize '11'H,
      proprietaryEFInfo { 
      fillPattern '00FF'H 
      }
    },
  createFCP :{
      fileDescriptor '4121'H,
      fileID '6f48'H,
      securityAttributesReferenced '06'H,
      efFileSize '14'H
    },
  createFCP :{
      fileDescriptor '4121'H,     
      fileID '6f52'H,
      securityAttributesReferenced '05'H,
      efFileSize '09'H
    },
    fillFileContent : 'ffffffffffffffff07'H,
  createFCP :{
     	fileDescriptor '4121'H,     
      fileID '6f53'H,
      securityAttributesReferenced '05'H,
      efFileSize '0e'H
    },
    fillFileContent : 'ffffffffffffffffffffffffff01'H,
createFCP :{
      fileDescriptor '4121'H,     
      fileID '6f54'H,
      securityAttributesReferenced '06'H,
      efFileSize '17'H
    },
 createFCP :{
      fileDescriptor '4121'H,
      fileID '6f74'H,
      securityAttributesReferenced '05'H,
      efFileSize '10'H
    },
  createFCP :{
      fileDescriptor '4121'H,     
      fileID '6f78'H,
      securityAttributesReferenced '06'H,
      efFileSize '02'H
    },
  createFCP :{
      fileDescriptor '4121'H,     
      fileID '6f7b'H,
      securityAttributesReferenced '05'H,
      efFileSize '1e'H,
      proprietaryEFInfo { 
      fillPattern '64F00064F02064F04064F07064F08064F03064F011FF'H 
      }
    },
  createFCP :{
      fileDescriptor '4121'H,     
      fileID '6f7e'H,
      securityAttributesReferenced '0b'H,
      efFileSize '0b'H
    },
    fillFileContent : 'FFFFFFFFFFFFFFFFFEFF01'H,
  createFCP :{
     	fileDescriptor '4121'H,     
      fileID '6fad'H,
      securityAttributesReferenced '08'H,
      efFileSize '03'H
    },
    fillFileContent : '000000'H,
  createFCP :{
      fileDescriptor '4121'H,     
      fileID '6fae'H,
      securityAttributesReferenced '08'H,
      efFileSize '01'H
    },
    fillFileContent : '03'H,
 createFCP :{
      fileDescriptor '4121'H,     
      fileID '6fb7'H,
      securityAttributesReferenced '08'H,
      efFileSize '0c'H
    }
}
}
pe-end ProfileElement ::= end : {
  end-header {
    mandated NULL,
    identification 99
  }
}