
package com.whty.efs.webservice.es.message;

import javax.xml.ws.Endpoint;

import com.whty.efs.webservice.es.SmSrES1PortImpl;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-08T17:55:13.050+08:00
 * Generated source version: 3.1.7
 * 
 */
 
public class ES1SmSr_SmSrES1Port_Server{

    protected ES1SmSr_SmSrES1Port_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new SmSrES1PortImpl();
        String address = "http://gsma.org/esim-messaging/3/ES1/ES1SmSrService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ES1SmSr_SmSrES1Port_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
