package com.whty.efs.webservice.es.message;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-12-26T09:43:20.010+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://namespaces.gsma.org/esim-messaging/3", name = "ES2Mno")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ES2Mno {

    @WebMethod(operationName = "ES2-EnableProfile")
    @Action(input = "http://gsma.com/ES2/PlatformManagement/ES2-EnableProfileRequest", output = "http://gsma.com/ES2/PlatformManagement/ES2-EnableProfileResponse")
    @WebResult(name = "ES2-EnableProfileResponse", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3", partName = "parameters")
    public ES2EnableProfileResponse es2EnableProfile(
        @WebParam(partName = "parameters", name = "ES2-EnableProfileRequest", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3")
        ES2EnableProfileRequest parameters
    );

    @WebMethod(operationName = "ES2-DownloadProfile")
    @Action(input = "http://gsma.com/ES2/ProfileManagement/ES2-DownloadProfileRequest", output = "http://gsma.com/ES2/PlatformManagement/ES2-DownloadProfileResponse")
    @WebResult(name = "ES2-DownloadProfileResponse", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3", partName = "parameters")
    public ES2DownloadProfileResponse es2DownloadProfile(
        @WebParam(partName = "parameters", name = "ES2-DownloadProfileRequest", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3")
        ES2DownloadProfileRequest parameters
    );

    @WebMethod(operationName = "ES2-GetEIS")
    @Action(input = "http://gsma.com/ES2/DataPreparation/ES2-GetEISRequest", output = "http://gsma.com/ES2/DataPreparation/ES2-GetEISResponse")
    @WebResult(name = "ES2-GetEISResponse", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3", partName = "parameters")
    public ES2GetEISResponse es2GetEIS(
        @WebParam(partName = "parameters", name = "ES2-GetEISRequest", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3")
        ES2GetEISRequest parameters
    );

    @WebMethod(operationName = "ES2-UpdateSubscriptionAddress")
    @Action(input = "http://gsma.com/ES2/ProfileManagement/ES2-UpdateSubscriptionAddressRequest", output = "http://gsma.com/ES2/ProfileManagement/ES2-UpdateSubscriptionAddressResponse")
    @WebResult(name = "ES2-UpdateSubscriptionAddressResponse", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3", partName = "parameters")
    public ES2UpdateSubscriptionAddressResponse es2UpdateSubscriptionAddress(
        @WebParam(partName = "parameters", name = "ES2-UpdateSubscriptionAddressRequest", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3")
        ES2UpdateSubscriptionAddressRequest parameters
    );

    @WebMethod(operationName = "ES2-DisableProfile")
    @Action(input = "http://gsma.com/ES2/PlatformManagement/ES2-DisableProfileRequest", output = "http://gsma.com/ES2/PlatformManagement/ES2-DisableProfileResponse")
    @WebResult(name = "ES2-DisableProfileResponse", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3", partName = "parameters")
    public ES2DisableProfileResponse es2DisableProfile(
        @WebParam(partName = "parameters", name = "ES2-DisableProfileRequest", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3")
        ES2DisableProfileRequest parameters
    );

    @WebMethod(operationName = "ES2-DeleteProfile")
    @Action(input = "http://gsma.com/ES2/PlatformManagement/ES2-DeleteProfileRequest", output = "http://gsma.com/ES2/PlatformManagement/ES2-DeleteProfileResponse")
    @WebResult(name = "ES2-DeleteProfileResponse", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3", partName = "parameters")
    public ES2DeleteProfileResponse es2DeleteProfile(
        @WebParam(partName = "parameters", name = "ES2-DeleteProfileRequest", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3")
        ES2DeleteProfileRequest parameters
    );

    @WebMethod(operationName = "ES2-UpdatePolicyRules")
    @Action(input = "http://gsma.com/ES2/ProfileManagement/ES2-UpdatePolicyRulesRequest", output = "http://gsma.com/ES2/ProfileManagement/ES2-UpdatePolicyRulesResponse")
    @WebResult(name = "ES2-UpdatePolicyRulesResponse", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3", partName = "parameters")
    public ES2UpdatePolicyRulesResponse es2UpdatePolicyRules(
        @WebParam(partName = "parameters", name = "ES2-UpdatePolicyRulesRequest", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3")
        ES2UpdatePolicyRulesRequest parameters
    );
}
