
package com.whty.efs.webservice.es.message;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-12T13:37:17.386+08:00
 * Generated source version: 3.1.7
 * 
 */
public final class ES2Mno_MnoES2Port_Client {

    private static final QName SERVICE_NAME = new QName("http://namespaces.gsma.org/esim-messaging/3", "ES2MnoService");

    private ES2Mno_MnoES2Port_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ES2MnoService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ES2MnoService ss = new ES2MnoService(wsdlURL, SERVICE_NAME);
        ES2Mno port = ss.getMnoES2Port();  
        
        {
        	System.out.println("Invoking es2EnableProfile...");
        	com.whty.efs.webservice.es.message.ES2EnableProfileRequest _es2EnableProfile_parameters = null;
        	com.whty.efs.webservice.es.message.ES2EnableProfileResponse _es2EnableProfile__return = port.es2EnableProfile(_es2EnableProfile_parameters);
        	System.out.println("es2EnableProfile.result=" + _es2EnableProfile__return);


        }
        {
            System.out.println("Invoking es2DownloadProfile...");
            com.whty.efs.webservice.es.message.ES2DownloadProfileRequest _es2DownloadProfile_parameters = null;
            com.whty.efs.webservice.es.message.ES2DownloadProfileResponse _es2DownloadProfile__return = port.es2DownloadProfile(_es2DownloadProfile_parameters);
            System.out.println("es2DownloadProfile.result=" + _es2DownloadProfile__return);


        }
        {
        System.out.println("Invoking es2GetEIS...");
        com.whty.efs.webservice.es.message.ES2GetEISRequest _es2GetEIS_parameters = null;
        com.whty.efs.webservice.es.message.ES2GetEISResponse _es2GetEIS__return = port.es2GetEIS(_es2GetEIS_parameters);
        System.out.println("es2GetEIS.result=" + _es2GetEIS__return);


        }
        {
        System.out.println("Invoking es2UpdateSubscriptionAddress...");
        com.whty.efs.webservice.es.message.ES2UpdateSubscriptionAddressRequest _es2UpdateSubscriptionAddress_parameters = null;
        com.whty.efs.webservice.es.message.ES2UpdateSubscriptionAddressResponse _es2UpdateSubscriptionAddress__return = port.es2UpdateSubscriptionAddress(_es2UpdateSubscriptionAddress_parameters);
        System.out.println("es2UpdateSubscriptionAddress.result=" + _es2UpdateSubscriptionAddress__return);


        }
        {
        System.out.println("Invoking es2DisableProfile...");
        com.whty.efs.webservice.es.message.ES2DisableProfileRequest _es2DisableProfile_parameters = null;
        com.whty.efs.webservice.es.message.ES2DisableProfileResponse _es2DisableProfile__return = port.es2DisableProfile(_es2DisableProfile_parameters);
        System.out.println("es2DisableProfile.result=" + _es2DisableProfile__return);


        }
        {
        System.out.println("Invoking es2DeleteProfile...");
        com.whty.efs.webservice.es.message.ES2DeleteProfileRequest _es2DeleteProfile_parameters = null;
        com.whty.efs.webservice.es.message.ES2DeleteProfileResponse _es2DeleteProfile__return = port.es2DeleteProfile(_es2DeleteProfile_parameters);
        System.out.println("es2DeleteProfile.result=" + _es2DeleteProfile__return);


        }
        {
        System.out.println("Invoking es2UpdatePolicyRules...");
        com.whty.efs.webservice.es.message.ES2UpdatePolicyRulesRequest _es2UpdatePolicyRules_parameters = null;
        com.whty.efs.webservice.es.message.ES2UpdatePolicyRulesResponse _es2UpdatePolicyRules__return = port.es2UpdatePolicyRules(_es2UpdatePolicyRules_parameters);
        System.out.println("es2UpdatePolicyRules.result=" + _es2UpdatePolicyRules__return);


        }

        System.exit(0);
    }

}
