
package com.whty.efs.webservice.es.message;

import javax.xml.ws.Endpoint;

import com.whty.efs.webservice.es.SmSrES3PortImpl;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-01-06T15:06:23.829+08:00
 * Generated source version: 3.1.9
 * 
 */
 
public class ES3SmSr_SmSrES3Port_Server{

    protected ES3SmSr_SmSrES3Port_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new SmSrES3PortImpl();
        String address = "http://gsma.org/esim-messaging/3/ES3/ES3SmSrService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ES3SmSr_SmSrES3Port_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
