package com.whty.efs.webservice.es.message;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-01-06T15:06:23.831+08:00
 * Generated source version: 3.1.9
 * 
 */
@WebServiceClient(name = "ES3SmSrService", 
                  wsdlLocation = "file:WebServicesAPI1/ES3_SMSR.wsdl",
                  targetNamespace = "http://namespaces.gsma.org/esim-messaging/3") 
public class ES3SmSrService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://namespaces.gsma.org/esim-messaging/3", "ES3SmSrService");
    public final static QName SmSrES3Port = new QName("http://namespaces.gsma.org/esim-messaging/3", "SmSrES3Port");
    static {
        URL url = null;
        try {
            url = new URL("file:WebServicesAPI1/ES3_SMSR.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ES3SmSrService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:WebServicesAPI1/ES3_SMSR.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ES3SmSrService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ES3SmSrService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ES3SmSrService() {
        super(WSDL_LOCATION, SERVICE);
    }
    




    /**
     *
     * @return
     *     returns ES3SmSr
     */
    @WebEndpoint(name = "SmSrES3Port")
    public ES3SmSr getSmSrES3Port() {
        return super.getPort(SmSrES3Port, ES3SmSr.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ES3SmSr
     */
    @WebEndpoint(name = "SmSrES3Port")
    public ES3SmSr getSmSrES3Port(WebServiceFeature... features) {
        return super.getPort(SmSrES3Port, ES3SmSr.class, features);
    }

}
