
package com.whty.efs.webservice.es.message;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-10-26T17:12:40.260+08:00
 * Generated source version: 3.1.7
 * 
 */
public final class ES4Mno_MnoES4Port_Client {

    private static final QName SERVICE_NAME = new QName("http://namespaces.gsma.org/esim-messaging/3", "ES4MnoService");

    private ES4Mno_MnoES4Port_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ES4MnoService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ES4MnoService ss = new ES4MnoService(wsdlURL, SERVICE_NAME);
        ES4Mno port = ss.getMnoES4Port();  
        
        {
        System.out.println("Invoking es4GetEIS...");
        com.whty.efs.webservice.es.message.ES4GetEISRequest _es4GetEIS_parameters = null;
        com.whty.efs.webservice.es.message.ES4GetEISResponse _es4GetEIS__return = port.es4GetEIS(_es4GetEIS_parameters);
        System.out.println("es4GetEIS.result=" + _es4GetEIS__return);


        }
        {
            System.out.println("Invoking es4DeleteProfile...");
            com.whty.efs.webservice.es.message.ES4DeleteProfileRequest _es4DeleteProfile_parameters = null;
            com.whty.efs.webservice.es.message.ES4DeleteProfileResponse _es4DeleteProfile__return = port.es4DeleteProfile(_es4DeleteProfile_parameters);
            System.out.println("es4DeleteProfile.result=" + _es4DeleteProfile__return);


            }
            {
            System.out.println("Invoking es4SMSRChange...");
            com.whty.efs.webservice.es.message.ES4SMSRChangeRequest _es4SMSRChange_parameters = null;
            com.whty.efs.webservice.es.message.ES4SMSRChangeResponse _es4SMSRChange__return = port.es4SMSRChange(_es4SMSRChange_parameters);
            System.out.println("es4SMSRChange.result=" + _es4SMSRChange__return);


            }
            {
            System.out.println("Invoking es4AuditEIS...");
            com.whty.efs.webservice.es.message.ES4AuditEISRequest _es4AuditEIS_parameters = null;
            com.whty.efs.webservice.es.message.ES4AuditEISResponse _es4AuditEIS__return = port.es4AuditEIS(_es4AuditEIS_parameters);
            System.out.println("es4AuditEIS.result=" + _es4AuditEIS__return);


            }
            {
            System.out.println("Invoking es4PrepareSMSRChange...");
            com.whty.efs.webservice.es.message.ES4PrepareSMSRChangeRequest _es4PrepareSMSRChange_parameters = null;
            com.whty.efs.webservice.es.message.ES4PrepareSMSRChangeResponse _es4PrepareSMSRChange__return = port.es4PrepareSMSRChange(_es4PrepareSMSRChange_parameters);
            System.out.println("es4PrepareSMSRChange.result=" + _es4PrepareSMSRChange__return);


            }
            {
            System.out.println("Invoking es4UpdateSubscriptionAddress...");
            com.whty.efs.webservice.es.message.ES4UpdateSubscriptionAddressRequest _es4UpdateSubscriptionAddress_parameters = null;
            com.whty.efs.webservice.es.message.ES4UpdateSubscriptionAddressResponse _es4UpdateSubscriptionAddress__return = port.es4UpdateSubscriptionAddress(_es4UpdateSubscriptionAddress_parameters);
            System.out.println("es4UpdateSubscriptionAddress.result=" + _es4UpdateSubscriptionAddress__return);


            }
            {
            System.out.println("Invoking es4EnableProfile...");
            com.whty.efs.webservice.es.message.ES4EnableProfileRequest _es4EnableProfile_parameters = null;
            com.whty.efs.webservice.es.message.ES4EnableProfileResponse _es4EnableProfile__return = port.es4EnableProfile(_es4EnableProfile_parameters);
            System.out.println("es4EnableProfile.result=" + _es4EnableProfile__return);


            }
            {
            System.out.println("Invoking es4DisableProfile...");
            com.whty.efs.webservice.es.message.ES4DisableProfileRequest _es4DisableProfile_parameters = null;
            com.whty.efs.webservice.es.message.ES4DisableProfileResponse _es4DisableProfile__return = port.es4DisableProfile(_es4DisableProfile_parameters);
            System.out.println("es4DisableProfile.result=" + _es4DisableProfile__return);


            }
            {
            System.out.println("Invoking es4UpdatePolicyRules...");
            com.whty.efs.webservice.es.message.ES4UpdatePolicyRulesRequest _es4UpdatePolicyRules_parameters = null;
            com.whty.efs.webservice.es.message.ES4UpdatePolicyRulesResponse _es4UpdatePolicyRules__return = port.es4UpdatePolicyRules(_es4UpdatePolicyRules_parameters);
            System.out.println("es4UpdatePolicyRules.result=" + _es4UpdatePolicyRules__return);


            }


        System.exit(0);
    }

}
