package com.whty.efs.webservice.es.message;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-10-26T17:12:40.281+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://namespaces.gsma.org/esim-messaging/3", name = "ES4Mno")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ES4Mno {

    @WebMethod(operationName = "ES4-GetEIS")
    @Action(input = "http://gsma.com/ES4/PlatformManagement/ES4-GetEISRequest", output = "http://gsma.com/ES4/eUICCManagement/ES4-GetEISResponse")
    @WebResult(name = "ES4-GetEISResponse", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3", partName = "parameters")
    public ES4GetEISResponse es4GetEIS(
        @WebParam(partName = "parameters", name = "ES4-GetEISRequest", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3")
        ES4GetEISRequest parameters
    );
    @WebMethod(operationName = "ES4-DeleteProfile")
    @Action(input = "http://gsma.com/ES4/PlatformManagement/ES4-DeleteProfileRequest", output = "http://gsma.com/ES4/eUICCManagement/ES4-DeleteProfileResponse")
    @WebResult(name = "ES4-DeleteProfileResponse", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3", partName = "parameters")
    public ES4DeleteProfileResponse es4DeleteProfile(
        @WebParam(partName = "parameters", name = "ES4-DeleteProfileRequest", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3")
        ES4DeleteProfileRequest parameters
    );

    @WebMethod(operationName = "ES4-SMSRChange")
    @Action(input = "http://gsma.com/ES4/PlatformManagement/ES4-SMSRChangeRequest", output = "http://gsma.com/ES4/eUICCManagement/ES4-SMSRChangeResponse")
    @WebResult(name = "ES4-SMSRChangeResponse", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3", partName = "parameters")
    public ES4SMSRChangeResponse es4SMSRChange(
        @WebParam(partName = "parameters", name = "ES4-SMSRChangeRequest", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3")
        ES4SMSRChangeRequest parameters
    );

    @WebMethod(operationName = "ES4-AuditEIS")
    @Action(input = "http://gsma.com/ES4/PlatformManagement/ES4-AuditEISRequest", output = "http://gsma.com/ES4/eUICCManagement/ES4-AuditEISResponse")
    @WebResult(name = "ES4-AuditEISResponse", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3", partName = "parameters")
    public ES4AuditEISResponse es4AuditEIS(
        @WebParam(partName = "parameters", name = "ES4-AuditEISRequest", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3")
        ES4AuditEISRequest parameters
    );

    @WebMethod(operationName = "ES4-PrepareSMSRChange")
    @Action(input = "http://gsma.com/ES4/PlatformManagement/ES4-PrepareSMSRChangeRequest", output = "http://gsma.com/ES4/eUICCManagement/ES4-PrepareSMSRChangeResponse")
    @WebResult(name = "ES4-PrepareSMSRChangeResponse", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3", partName = "parameters")
    public ES4PrepareSMSRChangeResponse es4PrepareSMSRChange(
        @WebParam(partName = "parameters", name = "ES4-PrepareSMSRChangeRequest", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3")
        ES4PrepareSMSRChangeRequest parameters
    );

    @WebMethod(operationName = "ES4-UpdateSubscriptionAddress")
    @Action(input = "http://gsma.com/ES4/PlatformManagement/ES4-UpdateSubscriptionAddressRequest", output = "http://gsma.com/ES4/eUICCManagement/ES4-UpdateSubscriptionAddressResponse")
    @WebResult(name = "ES4-UpdateSubscriptionAddressResponse", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3", partName = "parameters")
    public ES4UpdateSubscriptionAddressResponse es4UpdateSubscriptionAddress(
        @WebParam(partName = "parameters", name = "ES4-UpdateSubscriptionAddressRequest", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3")
        ES4UpdateSubscriptionAddressRequest parameters
    );

    @WebMethod(operationName = "ES4-EnableProfile")
    @Action(input = "http://gsma.com/ES4/PlatformManagement/ES4-EnableProfileRequest", output = "http://gsma.com/ES4/eUICCManagement/ES4-EnableProfileResponse")
    @WebResult(name = "ES4-EnableProfileResponse", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3", partName = "parameters")
    public ES4EnableProfileResponse es4EnableProfile(
        @WebParam(partName = "parameters", name = "ES4-EnableProfileRequest", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3")
        ES4EnableProfileRequest parameters
    );

    @WebMethod(operationName = "ES4-DisableProfile")
    @Action(input = "http://gsma.com/ES4/PlatformManagement/ES4-DisableProfileRequest", output = "http://gsma.com/ES4/eUICCManagement/ES4-DisableProfileResponse")
    @WebResult(name = "ES4-DisableProfileResponse", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3", partName = "parameters")
    public ES4DisableProfileResponse es4DisableProfile(
        @WebParam(partName = "parameters", name = "ES4-DisableProfileRequest", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3")
        ES4DisableProfileRequest parameters
    );

    @WebMethod(operationName = "ES4-UpdatePolicyRules")
    @Action(input = "http://gsma.com/ES4/PlatformManagement/ES4-UpdatePolicyRulesRequest", output = "http://gsma.com/ES4/eUICCManagement/ES4-UpdatePolicyRulesResponse")
    @WebResult(name = "ES4-UpdatePolicyRulesResponse", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3", partName = "parameters")
    public ES4UpdatePolicyRulesResponse es4UpdatePolicyRules(
        @WebParam(partName = "parameters", name = "ES4-UpdatePolicyRulesRequest", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3")
        ES4UpdatePolicyRulesRequest parameters
    );
}
