/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.whty.efs.webservice.es;

import java.util.Date;
import java.util.GregorianCalendar;

import javax.jws.HandlerChain;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;

import org.apache.cxf.interceptor.InInterceptors;
import org.apache.cxf.interceptor.OutInterceptors;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.gson.Gson;
import com.whty.efs.webservice.es.message.ES2HandleProfileDeletedNotification;
import com.whty.efs.webservice.es.message.ES2HandleProfileDisabledNotification;
import com.whty.efs.webservice.es.message.ES2HandleProfileEnabledNotification;
import com.whty.efs.webservice.es.message.ES2HandleSMSRChangeNotification;
import com.whty.efs.webservice.es.message.ES2Mno;
import com.whty.efs.webservice.es.message.ExecutionStatusType;
import com.whty.efs.webservice.es.message.StatusCodeDataType;
import com.whty.efs.webservice.es.message.StatusType;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-12T13:37:17.402+08:00
 * Generated source version: 3.1.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "ES2MnoService",
                      portName = "MnoES2Port",
                      targetNamespace = "http://namespaces.gsma.org/esim-messaging/3",
                      wsdlLocation = "WebServicesAPI/ES2_MNO.wsdl",
                      endpointInterface = "com.whty.efs.webservice.es.message.ES2Mno")
@HandlerChain(file="/ws/chain/es-handler-chain.xml")
@InInterceptors(interceptors="org.apache.cxf.interceptor.LoggingInInterceptor")
@OutInterceptors(interceptors="com.whty.efs.webservice.interceptor.ESOutInterceptor")                  
public class MnoES2PortImpl implements ES2Mno {

    private static final Logger LOG = LoggerFactory.getLogger(MnoES2PortImpl.class);


    /* (non-Javadoc)
     * @see com.whty.efs.webservice.es.message.ES2Mno#es2HandleSMSRChangeNotification(com.whty.efs.webservice.es.message.ES2HandleSMSRChangeNotification2 parameters)*
     */
    public void es2HandleSMSRChangeNotification(ES2HandleSMSRChangeNotification parameters) { 
        LOG.info("Executing operation es2HandleSMSRChangeNotification");
        System.out.println(parameters);
        System.out.println("es2HandleSMSRChangeNotification=" + new Gson().toJson(parameters));
        try {
            com.whty.efs.webservice.es.message.ES2HandleSMSRChangeNotification _return = new ES2HandleSMSRChangeNotification();
            GregorianCalendar c = new GregorianCalendar();
            c.setTime(new Date());
            XMLGregorianCalendar processStart = DatatypeFactory.newInstance().newXMLGregorianCalendar(c);
            ExecutionStatusType statusType = new ExecutionStatusType();
            StatusCodeDataType dataType = new StatusCodeDataType();
            dataType.setSubject("01");
            dataType.setSubjectIdentifier("02");
            dataType.setReason("03");
            dataType.setMessage("04");
            statusType.setStatus(StatusType.EXECUTED_SUCCESS);
            statusType.setStatusCodeData(dataType);
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.whty.efs.webservice.es.message.ES2Mno#es2HandleProfileDisabledNotification(com.whty.efs.webservice.es.message.ES2HandleProfileDisabledNotification2 parameters)*
     */
    public void es2HandleProfileDisabledNotification(ES2HandleProfileDisabledNotification parameters) { 
        LOG.info("Executing operation es2HandleProfileDisabledNotification");
        System.out.println(parameters);
        System.out.println("es2HandleProfileDisabledNotification=" + new Gson().toJson(parameters));
        try {
        	com.whty.efs.webservice.es.message.ES2HandleProfileDisabledNotification _return = new ES2HandleProfileDisabledNotification();
            GregorianCalendar c = new GregorianCalendar();
            c.setTime(new Date());
            XMLGregorianCalendar processStart = DatatypeFactory.newInstance().newXMLGregorianCalendar(c);
            ExecutionStatusType statusType = new ExecutionStatusType();
            StatusCodeDataType dataType = new StatusCodeDataType();
            dataType.setSubject("01");
            dataType.setSubjectIdentifier("02");
            dataType.setReason("03");
            dataType.setMessage("04");
            statusType.setStatus(StatusType.EXECUTED_SUCCESS);
            statusType.setStatusCodeData(dataType);
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }
    
    /* (non-Javadoc)
     * @see com.whty.efs.webservice.es.message.ES2Mno#es2HandleProfileEnabledNotification(com.whty.efs.webservice.es.message.ES2HandleProfileEnabledNotification2 parameters)*
     */
    public void es2HandleProfileEnabledNotification(ES2HandleProfileEnabledNotification parameters) { 
        LOG.info("Executing operation es2HandleProfileEnabledNotification");
        System.out.println(parameters);
        System.out.println("es2HandleProfileEnabledNotification=" + new Gson().toJson(parameters));
        try {
        	com.whty.efs.webservice.es.message.ES2HandleProfileEnabledNotification _return = new ES2HandleProfileEnabledNotification();
            GregorianCalendar c = new GregorianCalendar();
            c.setTime(new Date());
            XMLGregorianCalendar processStart = DatatypeFactory.newInstance().newXMLGregorianCalendar(c);
            ExecutionStatusType statusType = new ExecutionStatusType();
            StatusCodeDataType dataType = new StatusCodeDataType();
            dataType.setSubject("01");
            dataType.setSubjectIdentifier("02");
            dataType.setReason("03");
            dataType.setMessage("04");
            statusType.setStatus(StatusType.EXECUTED_SUCCESS);
            statusType.setStatusCodeData(dataType);
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }
    
    /* (non-Javadoc)
     * @see com.whty.efs.webservice.es.message.ES2Mno#es2HandleProfileDeletedNotification(com.whty.efs.webservice.es.message.ES2HandleProfileDeletedNotification2 parameters)*
     */
    public void es2HandleProfileDeletedNotification(ES2HandleProfileDeletedNotification parameters) { 
        LOG.info("Executing operation es2HandleProfileDeletedNotification");
        System.out.println(parameters);
        System.out.println("es2HandleProfileDeletedNotification=" + new Gson().toJson(parameters));
        try {
        	com.whty.efs.webservice.es.message.ES2HandleProfileDeletedNotification _return = new ES2HandleProfileDeletedNotification();
            GregorianCalendar c = new GregorianCalendar();
            c.setTime(new Date());
            XMLGregorianCalendar processStart = DatatypeFactory.newInstance().newXMLGregorianCalendar(c);
            ExecutionStatusType statusType = new ExecutionStatusType();
            StatusCodeDataType dataType = new StatusCodeDataType();
            dataType.setSubject("01");
            dataType.setSubjectIdentifier("02");
            dataType.setReason("03");
            dataType.setMessage("04");
            statusType.setStatus(StatusType.EXECUTED_SUCCESS);
            statusType.setStatusCodeData(dataType);
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }
    
}
