package com.whty.efs.webservice.es.message;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-12T13:37:17.417+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://namespaces.gsma.org/esim-messaging/3", name = "ES2Mno")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ES2Mno {
    @WebMethod(operationName = "ES2-HandleProfileDeletedNotification")
    @Action(input = "http://gsma.com/ES2/PlatformManagement/ES2-HandleProfileDeletedNotification")
    @Oneway
    public void es2HandleProfileDeletedNotification(
        @WebParam(partName = "parameters", name = "ES2-HandleProfileDeletedNotification", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3")
        ES2HandleProfileDeletedNotification parameters
    );

    @WebMethod(operationName = "ES2-HandleSMSRChangeNotification")
    @Action(input = "http://gsma.com/ES2/eUICCManagement/ES2-HandleSMSRChangeNotification")
    @Oneway
    public void es2HandleSMSRChangeNotification(
        @WebParam(partName = "parameters", name = "ES2-HandleSMSRChangeNotification", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3")
        ES2HandleSMSRChangeNotification parameters
    );

    @WebMethod(operationName = "ES2-HandleProfileDisabledNotification")
    @Action(input = "http://gsma.com/ES2/PlatformManagement/ES2-HandleProfileDisabledNotification")
    @Oneway
    public void es2HandleProfileDisabledNotification(
        @WebParam(partName = "parameters", name = "ES2-HandleProfileDisabledNotification", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3")
        ES2HandleProfileDisabledNotification parameters
    );

    @WebMethod(operationName = "ES2-HandleProfileEnabledNotification")
    @Action(input = "http://gsma.com/ES2/PlatformManagement/ES2-HandleProfileEnabledNotification")
    @Oneway
    public void es2HandleProfileEnabledNotification(
        @WebParam(partName = "parameters", name = "ES2-HandleProfileEnabledNotification", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3")
        ES2HandleProfileEnabledNotification parameters
    );
}
