
package com.whty.efs.webservice.es.message;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-12T13:37:17.386+08:00
 * Generated source version: 3.1.7
 * 
 */
public final class ES2Mno_MnoES2Port_Client {

    private static final QName SERVICE_NAME = new QName("http://namespaces.gsma.org/esim-messaging/3", "ES2MnoService");

    private ES2Mno_MnoES2Port_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ES2MnoService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ES2MnoService ss = new ES2MnoService(wsdlURL, SERVICE_NAME);
        ES2Mno port = ss.getMnoES2Port();  
        
        {
        System.out.println("Invoking es2HandleProfileDeletedNotification...");
        com.whty.efs.webservice.es.message.ES2HandleProfileDeletedNotification _es2HandleProfileDeletedNotification_parameters = null;
        port.es2HandleProfileDeletedNotification(_es2HandleProfileDeletedNotification_parameters);


        }
        {
        System.out.println("Invoking es2HandleSMSRChangeNotification...");
        com.whty.efs.webservice.es.message.ES2HandleSMSRChangeNotification _es2HandleSMSRChangeNotification_parameters = null;
        port.es2HandleSMSRChangeNotification(_es2HandleSMSRChangeNotification_parameters);


        }
        {
        System.out.println("Invoking es2HandleProfileDisabledNotification...");
        com.whty.efs.webservice.es.message.ES2HandleProfileDisabledNotification _es2HandleProfileDisabledNotification_parameters = null;
        port.es2HandleProfileDisabledNotification(_es2HandleProfileDisabledNotification_parameters);


        }
        {
        System.out.println("Invoking es2HandleProfileEnabledNotification...");
        com.whty.efs.webservice.es.message.ES2HandleProfileEnabledNotification _es2HandleProfileEnabledNotification_parameters = null;
        port.es2HandleProfileEnabledNotification(_es2HandleProfileEnabledNotification_parameters);


        }
        System.exit(0);
    }

}
