
package com.whty.efs.webservice.es.message;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-01-05T16:53:40.127+08:00
 * Generated source version: 3.1.7
 * 
 */
public final class ES4Mno_MnoES4Port_Client {

    private static final QName SERVICE_NAME = new QName("http://namespaces.gsma.org/esim-messaging/3", "ES4MnoService");

    private ES4Mno_MnoES4Port_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ES4MnoService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ES4MnoService ss = new ES4MnoService(wsdlURL, SERVICE_NAME);
        ES4Mno port = ss.getMnoES4Port();  
        
        {
        System.out.println("Invoking es4HandleProfileEnabledNotification...");
        com.whty.efs.webservice.es.message.ES4HandleProfileEnabledNotification _es4HandleProfileEnabledNotification_parameters = null;
        port.es4HandleProfileEnabledNotification(_es4HandleProfileEnabledNotification_parameters);


        }
        {
        System.out.println("Invoking es4HandleSMSRChangeNotification...");
        com.whty.efs.webservice.es.message.ES4HandleSMSRChangeNotification _es4HandleSMSRChangeNotification_parameters = null;
        port.es4HandleSMSRChangeNotification(_es4HandleSMSRChangeNotification_parameters);


        }
        {
        System.out.println("Invoking es4HandleProfileDeletedNotification...");
        com.whty.efs.webservice.es.message.ES4HandleProfileDeletedNotification _es4HandleProfileDeletedNotification_parameters = null;
        port.es4HandleProfileDeletedNotification(_es4HandleProfileDeletedNotification_parameters);


        }
        {
        System.out.println("Invoking es4HandleProfileDisabledNotification...");
        com.whty.efs.webservice.es.message.ES4HandleProfileDisabledNotification _es4HandleProfileDisabledNotification_parameters = null;
        port.es4HandleProfileDisabledNotification(_es4HandleProfileDisabledNotification_parameters);


        }

        System.exit(0);
    }

}
