package com.whty.efs.webservice.es.message;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-01-05T16:53:40.159+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://namespaces.gsma.org/esim-messaging/3", name = "ES4Mno")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ES4Mno {

    @WebMethod(operationName = "ES4-HandleProfileEnabledNotification")
    @Action(input = "http://gsma.com/ES4/PlatformManagement/ES4-HandleProfileEnabledNotification")
    @Oneway
    public void es4HandleProfileEnabledNotification(
        @WebParam(partName = "parameters", name = "ES4-HandleProfileEnabledNotification", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3")
        ES4HandleProfileEnabledNotification parameters
    );

    @WebMethod(operationName = "ES4-HandleSMSRChangeNotification")
    @Action(input = "http://gsma.com/ES4/eUICCManagement/ES4-HandleSMSRChangeNotification")
    @Oneway
    public void es4HandleSMSRChangeNotification(
        @WebParam(partName = "parameters", name = "ES4-HandleSMSRChangeNotification", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3")
        ES4HandleSMSRChangeNotification parameters
    );

    @WebMethod(operationName = "ES4-HandleProfileDeletedNotification")
    @Action(input = "http://gsma.com/ES4/PlatformManagement/ES4-HandleProfileDeletedNotification")
    @Oneway
    public void es4HandleProfileDeletedNotification(
        @WebParam(partName = "parameters", name = "ES4-HandleProfileDeletedNotification", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3")
        ES4HandleProfileDeletedNotification parameters
    );

    @WebMethod(operationName = "ES4-HandleProfileDisabledNotification")
    @Action(input = "http://gsma.com/ES4/PlatformManagement/ES4-HandleProfileDisabledNotification")
    @Oneway
    public void es4HandleProfileDisabledNotification(
        @WebParam(partName = "parameters", name = "ES4-HandleProfileDisabledNotification", targetNamespace = "http://namespaces.gsma.org/esim-messaging/3")
        ES4HandleProfileDisabledNotification parameters
    );
}
