package com.whty.efs.webservice.es.message;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-01-05T16:53:40.167+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "ES4MnoService", 
                  wsdlLocation = "file:WebServicesAPI/ES4_MNO.wsdl",
                  targetNamespace = "http://namespaces.gsma.org/esim-messaging/3") 
public class ES4MnoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://namespaces.gsma.org/esim-messaging/3", "ES4MnoService");
    public final static QName MnoES4Port = new QName("http://namespaces.gsma.org/esim-messaging/3", "MnoES4Port");
    static {
        URL url = null;
        try {
            url = new URL("file:WebServicesAPI/ES4_MNO.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ES4MnoService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:WebServicesAPI/ES4_MNO.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ES4MnoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ES4MnoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ES4MnoService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    /*public ES4MnoService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ES4MnoService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ES4MnoService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    */




    /**
     *
     * @return
     *     returns ES4Mno
     */
    @WebEndpoint(name = "MnoES4Port")
    public ES4Mno getMnoES4Port() {
        return super.getPort(MnoES4Port, ES4Mno.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ES4Mno
     */
    @WebEndpoint(name = "MnoES4Port")
    public ES4Mno getMnoES4Port(WebServiceFeature... features) {
        return super.getPort(MnoES4Port, ES4Mno.class, features);
    }

}
