
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.whty.efs.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-31T16:36:21.720+08:00
 * Generated source version: 3.1.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "EnterFrontService",
                      portName = "EnterFrontServicePort",
                      targetNamespace = "http://www.tathing.com",
                      wsdlLocation = "http://localhost:8080/euicc-efs-container/webservice/EnterFrontService?wsdl",
                      endpointInterface = "com.whty.efs.client.IEnterFrontService")
                      
public class EnterFrontServicePortImpl implements IEnterFrontService {

    private static final Logger LOG = Logger.getLogger(EnterFrontServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.whty.efs.client.IEnterFrontService#appPersonial(com.whty.efs.client.AppPersonialRequest appPersonialRequest)*
     */
    public com.whty.efs.client.AppPersonialResponse appPersonial(AppPersonialRequest appPersonialRequest) { 
        LOG.info("Executing operation appPersonial");
        System.out.println(appPersonialRequest);
        try {
            com.whty.efs.client.AppPersonialResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.whty.efs.client.IEnterFrontService#appQuery(com.whty.efs.client.AppQueryRequest appQueryRequest)*
     */
    public com.whty.efs.client.AppQueryResponse appQuery(AppQueryRequest appQueryRequest) { 
        LOG.info("Executing operation appQuery");
        System.out.println(appQueryRequest);
        try {
            com.whty.efs.client.AppQueryResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
