package com.whty.efs.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-31T16:36:21.765+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "EnterFrontService", 
                  wsdlLocation = "http://localhost:8080/euicc-efs-container/webservice/EnterFrontService?wsdl",
                  targetNamespace = "http://www.tathing.com") 
public class EnterFrontService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.tathing.com", "EnterFrontService");
    public final static QName EnterFrontServicePort = new QName("http://www.tathing.com", "EnterFrontServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/euicc-efs-container/webservice/EnterFrontService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EnterFrontService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/euicc-efs-container/webservice/EnterFrontService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EnterFrontService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EnterFrontService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EnterFrontService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns IEnterFrontService
     */
    @WebEndpoint(name = "EnterFrontServicePort")
    public IEnterFrontService getEnterFrontServicePort() {
        return super.getPort(EnterFrontServicePort, IEnterFrontService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEnterFrontService
     */
    @WebEndpoint(name = "EnterFrontServicePort")
    public IEnterFrontService getEnterFrontServicePort(WebServiceFeature... features) {
        return super.getPort(EnterFrontServicePort, IEnterFrontService.class, features);
    }

}
