package com.whty.efs.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-31T16:36:21.749+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://www.tathing.com", name = "IEnterFrontService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IEnterFrontService {

    @WebMethod(operationName = "AppPersonial")
    @WebResult(name = "AppPersonialResponse", targetNamespace = "http://www.tathing.com", partName = "AppPersonialResponse")
    public AppPersonialResponse appPersonial(
        @WebParam(partName = "AppPersonialRequest", name = "AppPersonialRequest", targetNamespace = "http://www.tathing.com")
        AppPersonialRequest appPersonialRequest
    );

    @WebMethod(operationName = "AppQuery")
    @WebResult(name = "AppQueryResponse", targetNamespace = "http://www.tathing.com", partName = "AppQueryResponse")
    public AppQueryResponse appQuery(
        @WebParam(partName = "AppQueryRequest", name = "AppQueryRequest", targetNamespace = "http://www.tathing.com")
        AppQueryRequest appQueryRequest
    );
}
