
package com.whty.efs.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-31T16:36:21.690+08:00
 * Generated source version: 3.1.7
 * 
 */
public final class IEnterFrontService_EnterFrontServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.tathing.com", "EnterFrontService");

    private IEnterFrontService_EnterFrontServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = EnterFrontService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        EnterFrontService ss = new EnterFrontService(wsdlURL, SERVICE_NAME);
        IEnterFrontService port = ss.getEnterFrontServicePort();  
        
        {
        System.out.println("Invoking appPersonial...");
        com.whty.efs.client.AppPersonialRequest _appPersonial_appPersonialRequest = null;
        com.whty.efs.client.AppPersonialResponse _appPersonial__return = port.appPersonial(_appPersonial_appPersonialRequest);
        System.out.println("appPersonial.result=" + _appPersonial__return);


        }
        {
        System.out.println("Invoking appQuery...");
        com.whty.efs.client.AppQueryRequest _appQuery_appQueryRequest = null;
        com.whty.efs.client.AppQueryResponse _appQuery__return = port.appQuery(_appQuery_appQueryRequest);
        System.out.println("appQuery.result=" + _appQuery__return);


        }

        System.exit(0);
    }

}
